  // --- DATABASE OF WORDS (ordered by frequency) ---
            const initialWordList = [
                { id: 1, spanish: 'de', polish: 'z, od', example_es: 'Soy de Polonia.', example_pl: 'Jestem z Polski.' },
                { id: 2, spanish: 'la', polish: 'rodz. żeński', example_es: 'La casa es grande.', example_pl: 'Dom jest duży.' },
                { id: 3, spanish: 'que', polish: 'że, co, który', example_es: 'El libro que leo.', example_pl: 'Książka, którą czytam.' },
                { id: 4, spanish: 'el', polish: 'rodz. męski', example_es: 'El perro es blanco.', example_pl: 'Pies jest biały.' },
                { id: 5, spanish: 'en', polish: 'w', example_es: 'Estoy en casa.', example_pl: 'Jestem w domu.' },
                { id: 6, spanish: 'y', polish: 'i', example_es: 'Agua y pan.', example_pl: 'Woda i chleb.' },
                { id: 7, spanish: 'a', polish: 'do', example_es: 'Voy a la escuela.', example_pl: 'Idę do szkoły.' },
                { id: 8, spanish: 'los', polish: 'rodz. męski l.mn.', example_es: 'Los coches son rápidos.', example_pl: 'Samochody są szybkie.' },
                { id: 9, spanish: 'ser', polish: 'być (cechy stałe)', example_es: 'Yo soy alto.', example_pl: 'Jestem wysoki.' },
                { id: 10, spanish: 'se', polish: 'się', example_es: 'Él se llama Juan.', example_pl: 'On nazywa się Juan.' },
                { id: 11, spanish: 'no', polish: 'nie', example_es: 'No tengo tiempo.', example_pl: 'Nie mam czasu.' },
                { id: 12, spanish: 'haber', polish: 'być, mieć (pomocniczy)', example_es: 'He comido una manzana.', example_pl: 'Zjadłem jabłko.' },
                { id: 13, spanish: 'por', polish: 'przez, dla', example_es: 'Gracias por la ayuda.', example_pl: 'Dziękuję za pomoc.' },
                { id: 14, spanish: 'con', polish: 'z', example_es: 'Café con leche.', example_pl: 'Kawa z mlekiem.' },
                { id: 15, spanish: 'su', polish: 'jego, jej, ich', example_es: 'Es su libro.', example_pl: 'To jego/jej książka.' },
                { id: 16, spanish: 'para', polish: 'dla, żeby', example_es: 'Un regalo para ti.', example_pl: 'Prezent dla ciebie.' },
                { id: 17, spanish: 'como', polish: 'jak', example_es: 'Es tan alto como yo.', example_pl: 'Jest tak wysoki jak ja.' },
                { id: 18, spanish: 'estar', polish: 'być (cechy zmienne)', example_es: 'Estoy cansado.', example_pl: 'Jestem zmęczony.' },
                { id: 19, spanish: 'tener', polish: 'mieć', example_es: 'Tengo un gato.', example_pl: 'Mam kota.' },
                { id: 20, spanish: 'le', polish: 'jemu, jej', example_es: 'Le doy el libro.', example_pl: 'Daję mu/jej książkę.' },
                { id: 21, spanish: 'lo', polish: 'to, go', example_es: 'No lo sé.', example_pl: 'Nie wiem tego.' },
                { id: 22, spanish: 'todo', polish: 'wszystko', example_es: 'Como de todo.', example_pl: 'Jem wszystko.' },
                { id: 23, spanish: 'pero', polish: 'ale', example_es: 'Es caro, pero bueno.', example_pl: 'Jest drogie, ale dobre.' },
                { id: 24, spanish: 'más', polish: 'więcej', example_es: 'Quiero más agua.', example_pl: 'Chcę więcej wody.' },
                { id: 25, spanish: 'hacer', polish: 'robić', example_es: 'Hago mi tarea.', example_pl: 'Robię moje zadanie domowe.' },
                { id: 26, spanish: 'o', polish: 'lub', example_es: 'Té o café.', example_pl: 'Herbata czy kawa.' },
                { id: 27, spanish: 'poder', polish: 'móc', example_es: 'Puedo ayudarte.', example_pl: 'Mogę ci pomóc.' },
                { id: 28, spanish: 'decir', polish: 'powiedzieć', example_es: '¿Qué dices?', example_pl: 'Co mówisz?' },
                { id: 29, spanish: 'este', polish: 'ten', example_es: 'Este coche es nuevo.', example_pl: 'Ten samochód jest nowy.' },
                { id: 30, spanish: 'ir', polish: 'iść, jechać', example_es: 'Voy al cine.', example_pl: 'Idę do kina.' },
                { id: 31, spanish: 'otro', polish: 'inny', example_es: 'Quiero otro color.', example_pl: 'Chcę inny kolor.' },
                { id: 32, spanish: 'ese', polish: 'tamten', example_es: 'Ese libro es viejo.', example_pl: 'Tamta książka jest stara.' },
                { id: 33, spanish: 'si', polish: 'jeśli', example_es: 'Si llueve, no salgo.', example_pl: 'Jeśli pada, nie wychodzę.' },
                { id: 34, spanish: 'me', polish: 'mnie, mi', example_es: 'Me gusta la música.', example_pl: 'Podoba mi się muzyka.' },
                { id: 35, spanish: 'ya', polish: 'już', example_es: 'Ya he terminado.', example_pl: 'Już skończyłem.' },
                { id: 36, spanish: 'ver', polish: 'widzieć', example_es: 'Veo una película.', example_pl: 'Oglądam film.' },
                { id: 37, spanish: 'porque', polish: 'ponieważ', example_es: 'Estudio porque quiero aprender.', example_pl: 'Uczę się, ponieważ chcę się nauczyć.' },
                { id: 38, spanish: 'dar', polish: 'dawać', example_es: 'Te doy un consejo.', example_pl: 'Daję ci radę.' },
                { id: 39, spanish: 'cuando', polish: 'kiedy', example_es: 'Llámame cuando llegues.', example_pl: 'Zadzwoń, kiedy dotrzesz.' },
                { id: 40, spanish: 'él', polish: 'on', example_es: 'Él es mi amigo.', example_pl: 'On jest moim przyjacielem.' },
                { id: 41, spanish: 'muy', polish: 'bardzo', example_es: 'Estoy muy bien.', example_pl: 'Mam się bardzo dobrze.' },
                { id: 42, spanish: 'sin', polish: 'bez', example_es: 'Café sin azúcar.', example_pl: 'Kawa bez cukru.' },
                { id: 43, spanish: 'vez', polish: 'raz', example_es: 'Otra vez, por favor.', example_pl: 'Jeszcze raz, proszę.' },
                { id: 44, spanish: 'mucho', polish: 'dużo', example_es: 'Trabajo mucho.', example_pl: 'Dużo pracuję.' },
                { id: 45, spanish: 'saber', polish: 'wiedzieć', example_es: 'No sé la respuesta.', example_pl: 'Nie znam odpowiedzi.' },
                { id: 46, spanish: 'qué', polish: 'co? (pytanie)', example_es: '¿Qué hora es?', example_pl: 'Która jest godzina?' },
                { id: 47, spanish: 'sobre', polish: 'na, o', example_es: 'El libro está sobre la mesa.', example_pl: 'Książka jest na stole.' },
                { id: 48, spanish: 'mi', polish: 'mój', example_es: 'Es mi perro.', example_pl: 'To mój pies.' },
                { id: 49, spanish: 'alguno', polish: 'jakiś', example_es: '¿Tienes algún libro?', example_pl: 'Masz jakąś książkę?' },
                { id: 50, spanish: 'mismo', polish: 'ten sam', example_es: 'Vivimos en la misma calle.', example_pl: 'Mieszkamy na tej samej ulicy.' },
                { id: 51, spanish: 'mujer', polish: 'kobieta', example_es: 'La mujer lee un libro.', example_pl: 'Kobieta czyta książkę.' },
    { id: 52, spanish: 'yo', polish: 'ja', example_es: 'Yo soy estudiante.', example_pl: 'Jestem studentem.' },
    { id: 53, spanish: 'vida', polish: 'życie', example_es: 'La vida es bella.', example_pl: 'Życie jest piękne.' },
    { id: 54, spanish: 'gobierno', polish: 'rząd', example_es: 'El gobierno anunció nuevas leyes.', example_pl: 'Rząd ogłosił nowe prawa.' },
    { id: 55, spanish: 'país', polish: 'kraj', example_es: 'España es un país grande.', example_pl: 'Hiszpania to duży kraj.' },
    { id: 56, spanish: 'año', polish: 'rok', example_es: 'Este año ha sido largo.', example_pl: 'Ten rok był długi.' },
    { id: 57, spanish: 'tiempo', polish: 'czas, pogoda', example_es: 'No tengo tiempo.', example_pl: 'Nie mam czasu.' },
    { id: 58, spanish: 'presidente', polish: 'prezydent', example_es: 'El presidente dio un discurso.', example_pl: 'Prezydent wygłosił przemówienie.' },
    { id: 59, spanish: 'día', polish: 'dzień', example_es: 'Hoy es un buen día.', example_pl: 'Dziś jest dobry dzień.' },
    { id: 60, spanish: 'empresa', polish: 'firma', example_es: 'Trabajo en una empresa grande.', example_pl: 'Pracuję w dużej firmie.' },
    { id: 61, spanish: 'parte', polish: 'część', example_es: 'Esta es la primera parte.', example_pl: 'To jest pierwsza część.' },
    { id: 62, spanish: 'casa', polish: 'dom', example_es: 'Mi casa es tu casa.', example_pl: 'Mój dom jest twoim domem.' },
    { id: 63, spanish: 'trabajo', polish: 'praca', example_es: 'Me gusta mi trabajo.', example_pl: 'Lubię swoją pracę.' },
    { id: 64, spanish: 'gente', polish: 'ludzie', example_es: 'Hay mucha gente aquí.', example_pl: 'Jest tu dużo ludzi.' },
    { id: 65, spanish: 'estado', polish: 'stan, państwo', example_es: 'El estado de la economía es bueno.', example_pl: 'Stan gospodarki jest dobry.' },
    { id: 66, spanish: 'mundo', polish: 'świat', example_es: 'Quiero viajar por el mundo.', example_pl: 'Chcę podróżować po świecie.' },
    { id: 67, spanish: 'caso', polish: 'przypadek', example_es: 'Es un caso interesante.', example_pl: 'To interesujący przypadek.' },
    { id: 68, spanish: 'grupo', polish: 'grupa', example_es: 'Somos un grupo de amigos.', example_pl: 'Jesteśmy grupą przyjaciół.' },
    { id: 69, spanish: 'forma', polish: 'forma, kształt', example_es: 'Tiene una forma extraña.', example_pl: 'To ma dziwny kształt.' },
    { id: 70, spanish: 'sistema', polish: 'system', example_es: 'El sistema no funciona.', example_pl: 'System nie działa.' },
    { id: 71, spanish: 'ley', polish: 'prawo', example_es: 'Hay que respetar la ley.', example_pl: 'Trzeba szanować prawo.' },
    { id: 72, spanish: 'noche', polish: 'noc', example_es: 'Buenas noches.', example_pl: 'Dobranoc.' },
    { id: 73, spanish: 'hombre', polish: 'mężczyzna, człowiek', example_es: 'El hombre camina por la calle.', example_pl: 'Mężczyzna idzie ulicą.' },
    { id: 74, spanish: 'agua', polish: 'woda', example_es: 'Necesito un vaso de agua.', example_pl: 'Potrzebuję szklanki wody.' },
    { id: 75, spanish: 'madre', polish: 'matka', example_es: 'Mi madre es muy amable.', example_pl: 'Moja mama jest bardzo miła.' },
    { id: 76, spanish: 'padre', polish: 'ojciec', example_es: 'Su padre es doctor.', example_pl: 'Jego ojciec jest lekarzem.' },
    { id: 77, spanish: 'problema', polish: 'problem', example_es: 'No hay problema.', example_pl: 'Nie ma problemu.' },
    { id: 78, spanish: 'cosa', polish: 'rzecz', example_es: '¿Qué es esa cosa?', example_pl: 'Co to za rzecz?' },
    { id: 79, spanish: 'fin', polish: 'koniec', example_es: 'El fin de la película.', example_pl: 'Koniec filmu.' },
    { id: 80, spanish: 'mercado', polish: 'rynek', example_es: 'Voy al mercado a comprar fruta.', example_pl: 'Idę na rynek kupić owoce.' },
    { id: 81, spanish: 'punto', polish: 'punkt, kropka', example_es: 'Este es el punto principal.', example_pl: 'To jest główny punkt.' },
    { id: 82, spanish: 'ciudad', polish: 'miasto', example_es: 'Madrid es una ciudad grande.', example_pl: 'Madryt to duże miasto.' },
    { id: 83, spanish: 'mano', polish: 'ręka', example_es: 'Dame la mano.', example_pl: 'Podaj mi rękę.' },
    { id: 84, spanish: 'millón', polish: 'milion', example_es: 'Un millón de gracias.', example_pl: 'Milion podziękowań.' },
    { id: 85, spanish: 'manera', polish: 'sposób', example_es: 'De esta manera es más fácil.', example_pl: 'W ten sposób jest łatwiej.' },
    { id: 86, spanish: 'hora', polish: 'godzina', example_es: '¿Qué hora es?', example_pl: 'Która jest godzina?' },
    { id: 87, spanish: 'servicio', polish: 'usługa, serwis', example_es: 'El servicio al cliente es importante.', example_pl: 'Obsługa klienta jest ważna.' },
    { id: 88, spanish: 'programa', polish: 'program', example_es: 'Este programa de televisión es nuevo.', example_pl: 'Ten program telewizyjny jest nowy.' },
    { id: 89, spanish: 'persona', polish: 'osoba', example_es: 'Es una persona muy interesante.', example_pl: 'To bardzo interesująca osoba.' },
    { id: 90, spanish: 'salud', polish: 'zdrowie', example_es: 'La salud es lo más importante.', example_pl: 'Zdrowie jest najważniejsze.' },
    { id: 91, spanish: 'historia', polish: 'historia', example_es: 'Me gusta leer libros de historia.', example_pl: 'Lubię czytać książki historyczne.' },
    { id: 92, spanish: 'fuerza', polish: 'siła', example_es: 'Tiene mucha fuerza.', example_pl: 'On ma dużo siły.' },
    { id: 93, spanish: 'guerra', polish: 'wojna', example_es: 'La guerra es terrible.', example_pl: 'Wojna jest straszna.' },
    { id: 94, spanish: 'luz', polish: 'światło', example_es: 'Apaga la luz, por favor.', example_pl: 'Zgaś światło, proszę.' },
    { id: 95, spanish: 'nivel', polish: 'poziom', example_es: 'Es un nivel muy alto.', example_pl: 'To bardzo wysoki poziom.' },
    { id: 96, spanish: 'orden', polish: 'porządek, zamówienie', example_es: 'Poner la casa en orden.', example_pl: 'Uporządkować dom.' },
    { id: 97, spanish: 'paz', polish: 'pokój', example_es: 'Queremos la paz en el mundo.', example_pl: 'Chcemy pokoju na świecie.' },
    { id: 98, spanish: 'relación', polish: 'związek, relacja', example_es: 'Tienen una buena relación.', example_pl: 'Oni mają dobrą relację.' },
    { id: 99, spanish: 'libro', polish: 'książka', example_es: 'Estoy leyendo un libro.', example_pl: 'Czytam książkę.' },
    { id: 100, spanish: 'calle', polish: 'ulica', example_es: 'Vivo en esta calle.', example_pl: 'Mieszkam na tej ulicy.' },
    { id: 101, spanish: 'educación', polish: 'edukacja', example_es: 'La educación es fundamental.', example_pl: 'Edukacja jest fundamentalna.' },
    { id: 102, spanish: 'hijo', polish: 'syn', example_es: 'Mi hijo tiene cinco años.', example_pl: 'Mój syn ma pięć lat.' },
    { id: 103, spanish: 'idea', polish: 'pomysł', example_es: 'Tengo una buena idea.', example_pl: 'Mam dobry pomysł.' },
    { id: 104, spanish: 'mes', polish: 'miesiąc', example_es: 'El próximo mes es mi cumpleaños.', example_pl: 'W przyszłym miesiącu są moje urodziny.' },
    { id: 105, spanish: 'nombre', polish: 'imię, nazwa', example_es: '¿Cuál es tu nombre?', example_pl: 'Jak masz na imię?' },
    { id: 106, spanish: 'nuestro', polish: 'nasz', example_es: 'Este es nuestro coche.', example_pl: 'To jest nasz samochód.' },
    { id: 107, spanish: 'obra', polish: 'dzieło, praca', example_es: 'Es una obra de arte.', example_pl: 'To jest dzieło sztuki.' },
    { id: 108, spanish: 'ojo', polish: 'oko', example_es: 'Tengo los ojos azules.', example_pl: 'Mam niebieskie oczy.' },
    { id: 109, spanish: 'palabra', polish: 'słowo', example_es: 'Repite la palabra.', example_pl: 'Powtórz to słowo.' },
    { id: 110, spanish: 'pie', polish: 'stopa', example_es: 'Me duele el pie.', example_pl: 'Boli mnie stopa.' },
    { id: 111, spanish: 'política', polish: 'polityka', example_es: 'No me interesa la política.', example_pl: 'Nie interesuje mnie polityka.' },
    { id: 112, spanish: 'proceso', polish: 'proces', example_es: 'Es un proceso largo.', example_pl: 'To długi proces.' },
    { id: 113, spanish: 'razón', polish: 'powód, racja', example_es: 'Tienes razón.', example_pl: 'Masz rację.' },
    { id: 114, spanish: 'resultado', polish: 'wynik', example_es: 'El resultado fue positivo.', example_pl: 'Wynik był pozytywny.' },
    { id: 115, spanish: 'seguridad', polish: 'bezpieczeństwo', example_es: 'La seguridad es importante.', example_pl: 'Bezpieczeństwo jest ważne.' },
    { id: 116, spanish: 'semana', polish: 'tydzień', example_es: 'La próxima semana voy de vacaciones.', example_pl: 'W przyszłym tygodniu jadę na wakacje.' },
    { id: 117, spanish: 'sentido', polish: 'sens, zmysł', example_es: 'No tiene sentido.', example_pl: 'To nie ma sensu.' },
    { id: 118, spanish: 'siglo', polish: 'wiek, stulecie', example_es: 'Vivimos en el siglo XXI.', example_pl: 'Żyjemy w XXI wieku.' },
    { id: 119, spanish: 'sociedad', polish: 'społeczeństwo', example_es: 'La sociedad está cambiando.', example_pl: 'Społeczeństwo się zmienia.' },
    { id: 120, spanish: 'sol', polish: 'słońce', example_es: 'Hoy hace mucho sol.', example_pl: 'Dziś jest bardzo słonecznie.' },
    { id: 121, spanish: 'tipo', polish: 'typ, rodzaj', example_es: '¿Qué tipo de música te gusta?', example_pl: 'Jaki rodzaj muzyki lubisz?' },
    { id: 122, spanish: 'valor', polish: 'wartość', example_es: 'Tiene un gran valor sentimental.', example_pl: 'To ma dużą wartość sentymentalną.' },
    { id: 123, spanish: 'voz', polish: 'głos', example_es: 'Tiene una voz bonita.', example_pl: 'Ona ma ładny głos.' },
    { id: 124, spanish: 'acuerdo', polish: 'zgoda, umowa', example_es: 'Estamos de acuerdo.', example_pl: 'Zgadzamy się.' },
    { id: 125, spanish: 'acción', polish: 'akcja, działanie', example_es: 'La película tiene mucha acción.', example_pl: 'Ten film ma dużo akcji.' },
    { id: 126, spanish: 'actividad', polish: 'aktywność', example_es: 'La actividad física es buena para la salud.', example_pl: 'Aktywność fizyczna jest dobra dla zdrowia.' },
    { id: 127, spanish: 'aire', polish: 'powietrze', example_es: 'Necesito tomar el aire fresco.', example_pl: 'Muszę zaczerpnąć świeżego powietrza.' },
    { id: 128, spanish: 'amor', polish: 'miłość', example_es: 'El amor es ciego.', example_pl: 'Miłość jest ślepa.' },
    { id: 129, spanish: 'animal', polish: 'zwierzę', example_es: 'Mi animal favorito es el perro.', example_pl: 'Moim ulubionym zwierzęciem jest pies.' },
    { id: 130, spanish: 'arte', polish: 'sztuka', example_es: 'El arte moderno es interesante.', example_pl: 'Sztuka nowoczesna jest interesująca.' },
    { id: 131, spanish: 'autor', polish: 'autor', example_es: 'El autor del libro es famoso.', example_pl: 'Autor tej książki jest sławny.' },
    { id: 132, spanish: 'cabeza', polish: 'głowa', example_es: 'Me duele la cabeza.', example_pl: 'Boli mnie głowa.' },
    { id: 133, spanish: 'cambio', polish: 'zmiana', example_es: 'Necesito un cambio en mi vida.', example_pl: 'Potrzebuję zmiany w moim życiu.' },
    { id: 134, spanish: 'camino', polish: 'droga', example_es: 'Este es el camino correcto.', example_pl: 'To jest właściwa droga.' },
    { id: 135, spanish: 'capital', polish: 'stolica', example_es: 'Varsovia es la capital de Polonia.', example_pl: 'Warszawa jest stolicą Polski.' },
    { id: 136, spanish: 'cuerpo', polish: 'ciało', example_es: 'El cuerpo humano es complejo.', example_pl: 'Ciało ludzkie jest skomplikowane.' },
    { id: 137, spanish: 'derecho', polish: 'prawo (do czegoś)', example_es: 'Tienes derecho a una llamada.', example_pl: 'Masz prawo do jednego telefonu.' },
    { id: 138, spanish: 'dinero', polish: 'pieniądze', example_es: 'El dinero no lo es todo.', example_pl: 'Pieniądze to nie wszystko.' },
    { id: 139, spanish: 'dios', polish: 'bóg', example_es: 'Creer en Dios.', example_pl: 'Wierzyć w Boga.' },
    { id: 140, spanish: 'doctor', polish: 'lekarz', example_es: 'Tengo que ir al doctor.', example_pl: 'Muszę iść do lekarza.' },
    { id: 141, spanish: 'dolor', polish: 'ból', example_es: 'Siento un dolor en la espalda.', example_pl: 'Czuję ból w plecach.' },
    { id: 142, spanish: 'efecto', polish: 'efekt', example_es: 'El efecto fue inmediato.', example_pl: 'Efekt był natychmiastowy.' },
    { id: 143, spanish: 'ejemplo', polish: 'przykład', example_es: 'Por ejemplo, ...', example_pl: 'Na przykład, ...' },
    { id: 144, spanish: 'esperanza', polish: 'nadzieja', example_es: 'No pierdas la esperanza.', example_pl: 'Nie trać nadziei.' },
    { id: 145, spanish: 'familia', polish: 'rodzina', example_es: 'Mi familia es muy importante para mí.', example_pl: 'Moja rodzina jest dla mnie bardzo ważna.' },
    { id: 146, spanish: 'favor', polish: 'przysługa', example_es: '¿Me puedes hacer un favor?', example_pl: 'Możesz wyświadczyć mi przysługę?' },
    { id: 147, spanish: 'fiesta', polish: 'impreza, święto', example_es: 'La fiesta empieza a las ocho.', example_pl: 'Impreza zaczyna się o ósmej.' },
    { id: 148, spanish: 'frente', polish: 'czoło, front', example_es: 'Está en frente de la casa.', example_pl: 'To jest przed domem.' },
    { id: 149, spanish: 'futuro', polish: 'przyszłość', example_es: 'Pienso en mi futuro.', example_pl: 'Myślę o mojej przyszłości.' },
    { id: 150, spanish: 'ganas', polish: 'chęci', example_es: 'Tengo ganas de viajar.', example_pl: 'Mam ochotę podróżować.' },
            { id: 151, spanish: 'gobierno', polish: 'rząd', example_es: 'El gobierno tiene un plan.', example_pl: 'Rząd ma plan.' },
    { id: 152, spanish: 'gracia', polish: 'łaska, wdzięk', example_es: 'Lo hizo con mucha gracia.', example_pl: 'Zrobił to z dużym wdziękiem.' },
    { id: 153, spanish: 'hermano', polish: 'brat', example_es: 'Mi hermano es mayor que yo.', example_pl: 'Mój brat jest starszy ode mnie.' },
    { id: 154, spanish: 'hija', polish: 'córka', example_es: 'Su hija es muy inteligente.', example_pl: 'Jej córka jest bardzo inteligentna.' },
    { id: 155, spanish: 'importancia', polish: 'znaczenie, ważność', example_es: 'Esto no tiene importancia.', example_pl: 'To nie ma znaczenia.' },
    { id: 156, spanish: 'información', polish: 'informacja', example_es: 'Necesito más información.', example_pl: 'Potrzebuję więcej informacji.' },
    { id: 157, spanish: 'interés', polish: 'zainteresowanie', example_es: 'Tengo mucho interés en el arte.', example_pl: 'Bardzo interesuję się sztuką.' },
    { id: 158, spanish: 'juego', polish: 'gra', example_es: 'Es solo un juego.', example_pl: 'To tylko gra.' },
    { id: 159, spanish: 'lado', polish: 'strona, bok', example_es: 'Estoy a tu lado.', example_pl: 'Jestem po twojej stronie.' },
    { id: 160, spanish: 'lengua', polish: 'język', example_es: 'Hablo tres lenguas.', example_pl: 'Mówię w trzech językach.' },
    { id: 161, spanish: 'libertad', polish: 'wolność', example_es: 'La libertad de expresión es un derecho.', example_pl: 'Wolność słowa jest prawem.' },
    { id: 162, spanish: 'línea', polish: 'linia', example_es: 'Sigue la línea amarilla.', example_pl: 'Podążaj za żółtą linią.' },
    { id: 163, spanish: 'lugar', polish: 'miejsce', example_es: 'Este es mi lugar favorito.', example_pl: 'To jest moje ulubione miejsce.' },
    { id: 164, spanish: 'mar', polish: 'morze', example_es: 'Me gusta nadar en el mar.', example_pl: 'Lubię pływać w morzu.' },
    { id: 165, spanish: 'mayor', polish: 'większy, starszy', example_es: 'Es el mayor de la familia.', example_pl: 'On jest najstarszy w rodzinie.' },
    { id: 166, spanish: 'medio', polish: 'środek, połowa', example_es: 'Estamos en el medio del camino.', example_pl: 'Jesteśmy w połowie drogi.' },
    { id: 167, spanish: 'memoria', polish: 'pamięć', example_es: 'Tengo buena memoria.', example_pl: 'Mam dobrą pamięć.' },
    { id: 168, spanish: 'mente', polish: 'umysł', example_es: 'Abre tu mente.', example_pl: 'Otwórz swój umysł.' },
    { id: 169, spanish: 'minuto', polish: 'minuta', example_es: 'Espera un minuto.', example_pl: 'Poczekaj minutę.' },
    { id: 170, spanish: 'momento', polish: 'moment', example_es: 'Es un momento importante.', example_pl: 'To ważny moment.' },
    { id: 171, spanish: 'muerte', polish: 'śmierć', example_es: 'La muerte es parte de la vida.', example_pl: 'Śmierć jest częścią życia.' },
    { id: 172, spanish: 'movimiento', polish: 'ruch', example_es: 'El movimiento es vida.', example_pl: 'Ruch to życie.' },
    { id: 173, spanish: 'música', polish: 'muzyka', example_es: 'Escucho música todos los días.', example_pl: 'Słucham muzyki każdego dnia.' },
    { id: 174, spanish: 'necesidad', polish: 'potrzeba', example_es: 'Es una necesidad básica.', example_pl: 'To podstawowa potrzeba.' },
    { id: 175, spanish: 'negocio', polish: 'biznes, interes', example_es: 'Tengo un negocio familiar.', example_pl: 'Mam rodzinny biznes.' },
    { id: 176, spanish: 'niño', polish: 'dziecko, chłopiec', example_es: 'El niño juega en el parque.', example_pl: 'Chłopiec bawi się w parku.' },
    { id: 177, spanish: 'número', polish: 'numer, liczba', example_es: '¿Cuál es tu número de teléfono?', example_pl: 'Jaki jest twój numer telefonu?' },
    { id: 178, spanish: 'oportunidad', polish: 'okazja, szansa', example_es: 'Es una gran oportunidad.', example_pl: 'To wielka szansa.' },
    { id: 179, spanish: 'origen', polish: 'pochodzenie', example_es: '¿Cuál es el origen de esta palabra?', example_pl: 'Jakie jest pochodzenie tego słowa?' },
    { id: 180, spanish: 'país', polish: 'kraj', example_es: 'Francia es un país hermoso.', example_pl: 'Francja to piękny kraj.' },
    { id: 181, spanish: 'papel', polish: 'papier, rola', example_es: 'Necesito una hoja de papel.', example_pl: 'Potrzebuję kartki papieru.' },
    { id: 182, spanish: 'pasado', polish: 'przeszłość', example_es: 'No podemos cambiar el pasado.', example_pl: 'Nie możemy zmienić przeszłości.' },
    { id: 183, spanish: 'paso', polish: 'krok', example_es: 'Un paso a la vez.', example_pl: 'Krok po kroku.' },
    { id: 184, spanish: 'pecho', polish: 'klatka piersiowa, pierś', example_es: 'Siento un dolor en el pecho.', example_pl: 'Czuję ból w klatce piersiowej.' },
    { id: 185, spanish: 'película', polish: 'film', example_es: 'Vamos a ver una película.', example_pl: 'Chodźmy obejrzeć film.' },
    { id: 186, spanish: 'pensamiento', polish: 'myśl', example_es: 'Un pensamiento positivo.', example_pl: 'Pozytywna myśl.' },
    { id: 187, spanish: 'piso', polish: 'piętro, podłoga', example_es: 'Vivo en el tercer piso.', example_pl: 'Mieszkam na trzecim piętrze.' },
    { id: 188, spanish: 'placer', polish: 'przyjemność', example_es: 'Es un placer conocerte.', example_pl: 'Miło mi cię poznać.' },
    { id: 189, spanish: 'plan', polish: 'plan', example_es: '¿Cuál es el plan para hoy?', example_pl: 'Jaki jest plan na dziś?' },
    { id: 190, spanish: 'población', polish: 'populacja, ludność', example_es: 'La población mundial está creciendo.', example_pl: 'Ludność świata rośnie.' },
    { id: 191, spanish: 'poder', polish: 'władza, moc', example_es: 'El conocimiento es poder.', example_pl: 'Wiedza to potęga.' },
    { id: 192, spanish: 'precio', polish: 'cena', example_es: '¿Cuál es el precio?', example_pl: 'Jaka jest cena?' },
    { id: 193, spanish: 'principio', polish: 'początek, zasada', example_es: 'Al principio, todo era oscuro.', example_pl: 'Na początku wszystko było ciemne.' },
    { id: 194, spanish: 'profesor', polish: 'nauczyciel', example_es: 'El profesor explica la lección.', example_pl: 'Nauczyciel tłumaczy lekcję.' },
    { id: 195, spanish: 'pueblo', polish: 'miasteczko, lud', example_es: 'Vivo en un pueblo pequeño.', example_pl: 'Mieszkam w małym miasteczku.' },
    { id: 196, spanish: 'puerta', polish: 'drzwi', example_es: 'Cierra la puerta, por favor.', example_pl: 'Zamknij drzwi, proszę.' },
    { id: 197, spanish: 'puesto', polish: 'stanowisko, miejsce', example_es: 'Tengo un nuevo puesto de trabajo.', example_pl: 'Mam nowe stanowisko pracy.' },
    { id: 198, spanish: 'realidad', polish: 'rzeczywistość', example_es: 'La realidad es diferente.', example_pl: 'Rzeczywistość jest inna.' },
    { id: 199, spanish: 'resto', polish: 'reszta', example_es: 'El resto es historia.', example_pl: 'Reszta jest historią.' },
    { id: 200, spanish: 'rey', polish: 'król', example_es: 'El rey vive en un palacio.', example_pl: 'Król mieszka w pałacu.' },
    { id: 201, spanish: 'río', polish: 'rzeka', example_es: 'El río Amazonas es muy largo.', example_pl: 'Rzeka Amazonka jest bardzo długa.' },
    { id: 202, spanish: 'ropa', polish: 'ubranie', example_es: 'Necesito comprar ropa nueva.', example_pl: 'Muszę kupić nowe ubrania.' },
    { id: 203, spanish: 'saber', polish: 'wiedza', example_es: 'El saber no ocupa lugar.', example_pl: 'Wiedza nie zajmuje miejsca.' },
    { id: 204, spanish: 'sala', polish: 'salon, sala', example_es: 'Estamos en la sala de estar.', example_pl: 'Jesteśmy w salonie.' },
    { id: 205, spanish: 'sangre', polish: 'krew', example_es: 'La sangre es roja.', example_pl: 'Krew jest czerwona.' },
    { id: 206, spanish: 'segundo', polish: 'sekunda', example_es: 'Espera un segundo.', example_pl: 'Poczekaj sekundę.' },
    { id: 207, spanish: 'señor', polish: 'pan', example_es: 'Buenos días, señor.', example_pl: 'Dzień dobry, proszę pana.' },
    { id: 208, spanish: 'serie', polish: 'seria, serial', example_es: 'Veo una serie en Netflix.', example_pl: 'Oglądam serial na Netflixie.' },
    { id: 209, spanish: 'sexo', polish: 'płeć', example_es: 'Sexo masculino o femenino.', example_pl: 'Płeć męska czy żeńska.' },
    { id: 210, spanish: 'silencio', polish: 'cisza', example_es: 'Silencio, por favor.', example_pl: 'Cisza, proszę.' },
    { id: 211, spanish: 'sitio', polish: 'miejsce', example_es: 'Busco un sitio para aparcar.', example_pl: 'Szukam miejsca do zaparkowania.' },
    { id: 212, spanish: 'situación', polish: 'sytuacja', example_es: 'La situación es complicada.', example_pl: 'Sytuacja jest skomplikowana.' },
    { id: 213, spanish: 'sueño', polish: 'sen, marzenie', example_es: 'Tengo mucho sueño.', example_pl: 'Jestem bardzo śpiący.' },
    { id: 214, spanish: 'suelo', polish: 'podłoga, ziemia', example_es: 'El libro está en el suelo.', example_pl: 'Książka leży na podłodze.' },
    { id: 215, spanish: 'suerte', polish: 'szczęście', example_es: '¡Buena suerte!', example_pl: 'Powodzenia!' },
    { id: 216, spanish: 'tema', polish: 'temat', example_es: 'El tema de la clase es interesante.', example_pl: 'Temat lekcji jest interesujący.' },
    { id: 217, spanish: 'tierra', polish: 'ziemia', example_es: 'La Tierra es un planeta.', example_pl: 'Ziemia jest planetą.' },
    { id: 218, spanish: 'tío', polish: 'wujek', example_es: 'Mi tío vive en México.', example_pl: 'Mój wujek mieszka w Meksyku.' },
    { id: 219, spanish: 'trabajador', polish: 'pracownik', example_es: 'Es un buen trabajador.', example_pl: 'On jest dobrym pracownikiem.' },
    { id: 220, spanish: 'tren', polish: 'pociąg', example_es: 'El tren llega a las cinco.', example_pl: 'Pociąg przyjeżdża o piątej.' },
    { id: 221, spanish: 'uso', polish: 'użycie', example_es: 'El uso del teléfono está prohibido.', example_pl: 'Używanie telefonu jest zabronione.' },
    { id: 222, spanish: 'vecino', polish: 'sąsiad', example_es: 'Mi vecino es muy ruidoso.', example_pl: 'Mój sąsiad jest bardzo głośny.' },
    { id: 223, spanish: 'verdad', polish: 'prawda', example_es: 'Dime la verdad.', example_pl: 'Powiedz mi prawdę.' },
    { id: 224, spanish: 'viaje', polish: 'podróż', example_es: 'El viaje fue largo.', example_pl: 'Podróż była długa.' },
    { id: 225, spanish: 'vino', polish: 'wino', example_es: 'Me gusta el vino tinto.', example_pl: 'Lubię czerwone wino.' },
    { id: 226, spanish: 'vista', polish: 'widok', example_es: 'La vista desde aquí es increíble.', example_pl: 'Widok stąd jest niesamowity.' },
    { id: 227, spanish: 'zona', polish: 'strefa, obszar', example_es: 'Es una zona peligrosa.', example_pl: 'To niebezpieczna strefa.' },
    { id: 228, spanish: 'boca', polish: 'usta', example_es: 'Abre la boca.', example_pl: 'Otwórz usta.' },
    { id: 229, spanish: 'brazo', polish: 'ramię', example_es: 'Me rompí el brazo.', example_pl: 'Złamałem ramię.' },
    { id: 230, spanish: 'calor', polish: 'ciepło, gorąco', example_es: 'Hace mucho calor.', example_pl: 'Jest bardzo gorąco.' },
    { id: 231, spanish: 'campo', polish: 'pole, wieś', example_es: 'Me gusta vivir en el campo.', example_pl: 'Lubię mieszkać na wsi.' },
    { id: 232, spanish: 'cáncer', polish: 'rak', example_es: 'El cáncer es una enfermedad grave.', example_pl: 'Rak to poważna choroba.' },
    { id: 233, spanish: 'capacidad', polish: 'zdolność, pojemność', example_es: 'Tiene una gran capacidad de aprendizaje.', example_pl: 'Ma dużą zdolność uczenia się.' },
    { id: 234, spanish: 'carácter', polish: 'charakter', example_es: 'Tiene un carácter fuerte.', example_pl: 'On ma silny charakter.' },
    { id: 235, spanish: 'carrera', polish: 'wyścig, kariera', example_es: 'Su carrera como actor fue exitosa.', example_pl: 'Jego kariera aktorska była udana.' },
    { id: 236, spanish: 'carro', polish: 'samochód (Am. Łac.)', example_es: 'Compré un carro nuevo.', example_pl: 'Kupiłem nowy samochód.' },
    { id: 237, spanish: 'carta', polish: 'list', example_es: 'Escribí una carta a mi abuela.', example_pl: 'Napisałem list do mojej babci.' },
    { id: 238, spanish: 'centro', polish: 'centrum', example_es: 'El centro de la ciudad está lejos.', example_pl: 'Centrum miasta jest daleko.' },
    { id: 239, spanish: 'cielo', polish: 'niebo', example_es: 'El cielo está azul.', example_pl: 'Niebo jest niebieskie.' },
    { id: 240, spanish: 'clase', polish: 'lekcja, klasa', example_es: 'Tengo clase de español.', example_pl: 'Mam lekcję hiszpańskiego.' },
    { id: 241, spanish: 'color', polish: 'kolor', example_es: 'Mi color favorito es el azul.', example_pl: 'Moim ulubionym kolorem jest niebieski.' },
    { id: 242, spanish: 'comida', polish: 'jedzenie', example_es: 'La comida está lista.', example_pl: 'Jedzenie jest gotowe.' },
    { id: 243, spanish: 'compañero', polish: 'kolega, partner', example_es: 'Es mi compañero de trabajo.', example_pl: 'On jest moim kolegą z pracy.' },
    { id: 244, spanish: 'corazón', polish: 'serce', example_es: 'Te quiero con todo mi corazón.', example_pl: 'Kocham cię całym sercem.' },
    { id: 245, spanish: 'cosa', polish: 'rzecz', example_es: 'No entiendo una cosa.', example_pl: 'Nie rozumiem jednej rzeczy.' },
    { id: 246, spanish: 'costa', polish: 'wybrzeże', example_es: 'Vivimos en la costa.', example_pl: 'Mieszkamy na wybrzeżu.' },
    { id: 247, spanish: 'crisis', polish: 'kryzys', example_es: 'Estamos en una crisis económica.', example_pl: 'Jesteśmy w kryzysie gospodarczym.' },
    { id: 248, spanish: 'cuarto', polish: 'pokój', example_es: 'Mi cuarto es pequeño.', example_pl: 'Mój pokój jest mały.' },
    { id: 249, spanish: 'cuenta', polish: 'rachunek', example_es: 'La cuenta, por favor.', example_pl: 'Rachunek, proszę.' },
    { id: 250, spanish: 'cultura', polish: 'kultura', example_es: 'La cultura española es muy rica.', example_pl: 'Kultura hiszpańska jest bardzo bogata.' },
    { id: 251, spanish: 'curso', polish: 'kurs', example_es: 'Estoy haciendo un curso de fotografía.', example_pl: 'Robię kurs fotografii.' },
    { id: 252, spanish: 'daño', polish: 'szkoda, krzywda', example_es: 'El accidente causó mucho daño.', example_pl: 'Wypadek spowodował wiele szkód.' },
    { id: 253, spanish: 'dedo', polish: 'palec', example_es: 'Me corté el dedo.', example_pl: 'Skaleczyłem się w palec.' },
    { id: 254, spanish: 'desarrollo', polish: 'rozwój', example_es: 'El desarrollo del niño es rápido.', example_pl: 'Rozwój dziecka jest szybki.' },
    { id: 255, spanish: 'deseo', polish: 'życzenie, pragnienie', example_es: 'Tengo un deseo.', example_pl: 'Mam życzenie.' },
    { id: 256, spanish: 'diferencia', polish: 'różnica', example_es: '¿Cuál es la diferencia?', example_pl: 'Jaka jest różnica?' },
    { id: 257, spanish: 'dirección', polish: 'adres, kierunek', example_es: '¿Cuál es tu dirección?', example_pl: 'Jaki jest twój adres?' },
    { id: 258, spanish: 'distancia', polish: 'odległość', example_es: 'La distancia es corta.', example_pl: 'Odległość jest krótka.' },
    { id: 259, spanish: 'duda', polish: 'wątpliwość', example_es: 'Tengo una duda.', example_pl: 'Mam wątpliwość.' },
    { id: 260, spanish: 'edad', polish: 'wiek', example_es: '¿Qué edad tienes?', example_pl: 'Ile masz lat?' },
    { id: 261, spanish: 'elección', polish: 'wybór', example_es: 'Fue una buena elección.', example_pl: 'To był dobry wybór.' },
    { id: 262, spanish: 'energía', polish: 'energia', example_es: 'Necesito más energía.', example_pl: 'Potrzebuję więcej energii.' },
    { id: 263, spanish: 'enfermedad', polish: 'choroba', example_es: 'La gripe es una enfermedad común.', example_pl: 'Grypa to powszechna choroba.' },
    { id: 264, spanish: 'equipo', polish: 'drużyna, sprzęt', example_es: 'Somos un buen equipo.', example_pl: 'Jesteśmy dobrą drużyną.' },
    { id: 265, spanish: 'error', polish: 'błąd', example_es: 'Cometí un error.', example_pl: 'Popełniłem błąd.' },
    { id: 266, spanish: 'espacio', polish: 'przestrzeń', example_es: 'Necesito más espacio.', example_pl: 'Potrzebuję więcej przestrzeni.' },
    { id: 267, spanish: 'espalda', polish: 'plecy', example_es: 'Me duele la espalda.', example_pl: 'Bolą mnie plecy.' },
    { id: 268, spanish: 'estación', polish: 'stacja, pora roku', example_es: 'La estación de tren está cerca.', example_pl: 'Stacja kolejowa jest blisko.' },
    { id: 269, spanish: 'estudio', polish: 'nauka, gabinet', example_es: 'El estudio es importante.', example_pl: 'Nauka jest ważna.' },
    { id: 270, spanish: 'etapa', polish: 'etap', example_es: 'Es una nueva etapa en mi vida.', example_pl: 'To nowy etap w moim życiu.' },
    { id: 271, spanish: 'éxito', polish: 'sukces', example_es: 'Te deseo mucho éxito.', example_pl: 'Życzę ci wielu sukcesów.' },
    { id: 272, spanish: 'experiencia', polish: 'doświadczenie', example_es: 'Fue una experiencia inolvidable.', example_pl: 'To było niezapomniane doświadczenie.' },
    { id: 273, spanish: 'expresión', polish: 'wyrażenie', example_es: 'Tiene una expresión triste.', example_pl: 'On ma smutny wyraz twarzy.' },
    { id: 274, spanish: 'falta', polish: 'brak', example_es: 'Me hace falta dinero.', example_pl: 'Brakuje mi pieniędzy.' },
    { id: 275, spanish: 'figura', polish: 'figura, postać', example_es: 'Es una figura histórica.', example_pl: 'To postać historyczna.' },
    { id: 276, spanish: 'flor', polish: 'kwiat', example_es: 'Me gustan las flores.', example_pl: 'Lubię kwiaty.' },
    { id: 277, spanish: 'fondo', polish: 'dno, tło', example_es: 'El fondo del mar.', example_pl: 'Dno morza.' },
    { id: 278, spanish: 'foto', polish: 'zdjęcie', example_es: 'Sácame una foto.', example_pl: 'Zrób mi zdjęcie.' },
    { id: 279, spanish: 'función', polish: 'funkcja', example_es: '¿Cuál es la función de este botón?', example_pl: 'Jaka jest funkcja tego przycisku?' },
    { id: 280, spanish: 'gas', polish: 'gaz', example_es: 'La cocina es de gas.', example_pl: 'Kuchnia jest na gaz.' },
    { id: 281, spanish: 'gesto', polish: 'gest', example_es: 'Fue un gesto amable.', example_pl: 'To był miły gest.' },
    { id: 282, spanish: 'golpe', polish: 'uderzenie', example_es: 'Recibió un golpe en la cabeza.', example_pl: 'Otrzymał uderzenie w głowę.' },
    { id: 283, spanish: 'grado', polish: 'stopień', example_es: 'Hoy hace 30 grados.', example_pl: 'Dziś jest 30 stopni.' },
    { id: 284, spanish: 'hambre', polish: 'głód', example_es: 'Tengo mucha hambre.', example_pl: 'Jestem bardzo głodny.' },
    { id: 285, spanish: 'hecho', polish: 'fakt, zdarzenie', example_es: 'Es un hecho histórico.', example_pl: 'To fakt historyczny.' },
    { id: 286, spanish: 'hospital', polish: 'szpital', example_es: 'El hospital está cerca.', example_pl: 'Szpital jest blisko.' },
    { id: 287, spanish: 'hotel', polish: 'hotel', example_es: 'Nos alojamos en un hotel.', example_pl: 'Zatrzymaliśmy się w hotelu.' },
    { id: 288, spanish: 'iglesia', polish: 'kościół', example_es: 'Vamos a la iglesia los domingos.', example_pl: 'Chodzimy do kościoła w niedziele.' },
    { id: 289, spanish: 'imagen', polish: 'obraz', example_es: 'Una imagen vale más que mil palabras.', example_pl: 'Jeden obraz jest wart więcej niż tysiąc słów.' },
    { id: 290, spanish: 'institución', polish: 'instytucja', example_es: 'Es una institución pública.', example_pl: 'To instytucja publiczna.' },
    { id: 291, spanish: 'isla', polish: 'wyspa', example_es: 'Es una isla desierta.', example_pl: 'To bezludna wyspa.' },
    { id: 292, spanish: 'jefe', polish: 'szef', example_es: 'Mi jefe es muy exigente.', example_pl: 'Mój szef jest bardzo wymagający.' },
    { id: 293, spanish: 'juicio', polish: 'sąd, proces', example_es: 'El juicio duró varios días.', example_pl: 'Proces trwał kilka dni.' },
    { id: 294, spanish: 'justicia', polish: 'sprawiedliwość', example_es: 'Buscamos justicia.', example_pl: 'Szukamy sprawiedliwości.' },
    { id: 295, spanish: 'labor', polish: 'praca, trud', example_es: 'Es una labor difícil.', example_pl: 'To trudna praca.' },
    { id: 296, spanish: 'lago', polish: 'jezioro', example_es: 'Nadamos en el lago.', example_pl: 'Pływaliśmy w jeziorze.' },
    { id: 297, spanish: 'lectura', polish: 'czytanie', example_es: 'La lectura es mi pasatiempo favorito.', example_pl: 'Czytanie to moje ulubione hobby.' },
    { id: 298, spanish: 'letra', polish: 'litera', example_es: '¿Cuál es la primera letra de tu nombre?', example_pl: 'Jaka jest pierwsza litera twojego imienia?' },
    { id: 299, spanish: 'lucha', polish: 'walka', example_es: 'La lucha por la libertad.', example_pl: 'Walka o wolność.' },
    { id: 300, spanish: 'mañana', polish: 'jutro, rano', example_es: 'Nos vemos mañana.', example_pl: 'Do zobaczenia jutro.' },
    { id: 301, spanish: 'máquina', polish: 'maszyna', example_es: 'Esta máquina es muy moderna.', example_pl: 'Ta maszyna jest bardzo nowoczesna.' },
    { id: 302, spanish: 'marca', polish: 'marka', example_es: '¿Qué marca de coche tienes?', example_pl: 'Jakiej marki masz samochód?' },
    { id: 303, spanish: 'medida', polish: 'miara, środek', example_es: 'Tomar medidas urgentes.', example_pl: 'Podjąć pilne środki.' },
    { id: 304, spanish: 'miedo', polish: 'strach', example_es: 'No tengas miedo.', example_pl: 'Nie bój się.' },
    { id: 305, spanish: 'miembro', polish: 'członek', example_es: 'Soy miembro de este club.', example_pl: 'Jestem członkiem tego klubu.' },
    { id: 306, spanish: 'mirada', polish: 'spojrzenie', example_es: 'Tiene una mirada intensa.', example_pl: 'Ma intensywne spojrzenie.' },
    { id: 307, spanish: 'modelo', polish: 'model', example_es: 'Es un modelo a seguir.', example_pl: 'To wzór do naśladowania.' },
    { id: 308, spanish: 'montaña', polish: 'góra', example_es: 'Me gusta escalar montañas.', example_pl: 'Lubię wspinać się po górach.' },
    { id: 309, spanish: 'motivo', polish: 'powód', example_es: 'No tengo ningún motivo para quejarme.', example_pl: 'Nie mam żadnego powodu do narzekań.' },
    { id: 310, spanish: 'mueble', polish: 'mebel', example_es: 'Compramos muebles nuevos.', example_pl: 'Kupiliśmy nowe meble.' },
    { id: 311, spanish: 'muerte', polish: 'śmierć', example_es: 'Nadie escapa a la muerte.', example_pl: 'Nikt nie ucieknie przed śmiercią.' },
    { id: 312, spanish: 'naturaleza', polish: 'natura', example_es: 'Me gusta estar en contacto con la naturaleza.', example_pl: 'Lubię być w kontakcie z naturą.' },
    { id: 313, spanish: 'niña', polish: 'dziewczynka', example_es: 'La niña está jugando.', example_pl: 'Dziewczynka się bawi.' },
    { id: 314, spanish: 'noticia', polish: 'wiadomość', example_es: 'Tengo buenas noticias.', example_pl: 'Mam dobre wieści.' },
    { id: 315, spanish: 'objetivo', polish: 'cel', example_es: 'Mi objetivo es aprender español.', example_pl: 'Moim celem jest nauczyć się hiszpańskiego.' },
    { id: 316, spanish: 'opción', polish: 'opcja', example_es: 'No tengo otra opción.', example_pl: 'Nie mam innej opcji.' },
    { id: 317, spanish: 'opinión', polish: 'opinia', example_es: 'En mi opinión, es una buena idea.', example_pl: 'Moim zdaniem to dobry pomysł.' },
    { id: 318, spanish: 'organización', polish: 'organizacja', example_es: 'Es una organización sin fines de lucro.', example_pl: 'To organizacja non-profit.' },
    { id: 319, spanish: 'palacio', polish: 'pałac', example_es: 'Visitamos el palacio real.', example_pl: 'Odwiedziliśmy pałac królewski.' },
    { id: 320, spanish: 'par', polish: 'para', example_es: 'Necesito un par de zapatos.', example_pl: 'Potrzebuję pary butów.' },
    { id: 321, spanish: 'pared', polish: 'ściana', example_es: 'El cuadro está en la pared.', example_pl: 'Obraz jest na ścianie.' },
    { id: 322, spanish: 'pareja', polish: 'para (osób)', example_es: 'Son una pareja feliz.', example_pl: 'Są szczęśliwą parą.' },
    { id: 323, spanish: 'partido', polish: 'mecz, partia', example_es: 'Vamos a ver el partido de fútbol.', example_pl: 'Idziemy obejrzeć mecz piłki nożnej.' },
    { id: 324, spanish: 'pelo', polish: 'włosy', example_es: 'Tiene el pelo largo.', example_pl: 'Ona ma długie włosy.' },
    { id: 325, spanish: 'pena', polish: 'smutek, szkoda', example_es: '¡Qué pena!', example_pl: 'Jaka szkoda!' },
    { id: 326, spanish: 'periódico', polish: 'gazeta', example_es: 'Leo el periódico por la mañana.', example_pl: 'Czytam gazetę rano.' },
    { id: 327, spanish: 'perro', polish: 'pies', example_es: 'El perro es el mejor amigo del hombre.', example_pl: 'Pies jest najlepszym przyjacielem człowieka.' },
    { id: 328, spanish: 'personaje', polish: 'postać', example_es: 'Es el personaje principal de la novela.', example_pl: 'To główny bohater powieści.' },
    { id: 329, spanish: 'peso', polish: 'waga', example_es: '¿Cuál es tu peso?', example_pl: 'Jaka jest twoja waga?' },
    { id: 330, spanish: 'piedra', polish: 'kamień', example_es: 'Tiró una piedra al agua.', example_pl: 'Wrzucił kamień do wody.' },
    { id: 331, spanish: 'piel', polish: 'skóra', example_es: 'Tiene la piel suave.', example_pl: 'Ma gładką skórę.' },
    { id: 332, spanish: 'pierna', polish: 'noga', example_es: 'Me duele la pierna.', example_pl: 'Boli mnie noga.' },
    { id: 333, spanish: 'pintura', polish: 'malarstwo, farba', example_es: 'Me gusta la pintura abstracta.', example_pl: 'Lubię malarstwo abstrakcyjne.' },
    { id: 334, spanish: 'planta', polish: 'roślina', example_es: 'Tengo muchas plantas en casa.', example_pl: 'Mam w domu dużo roślin.' },
    { id: 335, spanish: 'plaza', polish: 'plac', example_es: 'Nos encontramos en la plaza.', example_pl: 'Spotykamy się na placu.' },
    { id: 336, spanish: 'policía', polish: 'policja', example_es: 'Llama a la policía.', example_pl: 'Zadzwoń na policję.' },
    { id: 337, spanish: 'posición', polish: 'pozycja', example_es: 'Está en una buena posición.', example_pl: 'Jest w dobrej pozycji.' },
    { id: 338, spanish: 'posibilidad', polish: 'możliwość', example_es: 'Existe la posibilidad de que llueva.', example_pl: 'Istnieje możliwość, że będzie padać.' },
    { id: 339, spanish: 'pregunta', polish: 'pytanie', example_es: 'Tengo una pregunta.', example_pl: 'Mam pytanie.' },
    { id: 340, spanish: 'presencia', polish: 'obecność', example_es: 'Su presencia es importante.', example_pl: 'Jego obecność jest ważna.' },
    { id: 341, spanish: 'presente', polish: 'teraźniejszość, prezent', example_es: 'Vive en el presente.', example_pl: 'Żyj teraźniejszością.' },
    { id: 342, spanish: 'presupuesto', polish: 'budżet', example_es: 'Tenemos un presupuesto limitado.', example_pl: 'Mamy ograniczony budżet.' },
    { id: 343, spanish: 'prisa', polish: 'pośpiech', example_es: 'Tengo mucha prisa.', example_pl: 'Bardzo mi się śpieszy.' },
    { id: 344, spanish: 'producción', polish: 'produkcja', example_es: 'La producción ha aumentado.', example_pl: 'Produkcja wzrosła.' },
    { id: 345, spanish: 'producto', polish: 'produkt', example_es: 'Este es un producto de calidad.', example_pl: 'To produkt wysokiej jakości.' },
    { id: 346, spanish: 'propuesta', polish: 'propozycja', example_es: 'Es una propuesta interesante.', example_pl: 'To interesująca propozycja.' },
    { id: 347, spanish: 'proyecto', polish: 'projekt', example_es: 'Estoy trabajando en un nuevo proyecto.', example_pl: 'Pracuję nad nowym projektem.' },
    { id: 348, spanish: 'prueba', polish: 'dowód, test', example_es: 'No hay prueba de ello.', example_pl: 'Nie ma na to dowodu.' },
    { id: 349, spanish: 'radio', polish: 'radio', example_es: 'Escucho la radio en el coche.', example_pl: 'Słucham radia w samochodzie.' },
    { id: 350, spanish: 'recuerdo', polish: 'wspomnienie', example_es: 'Tengo buenos recuerdos de mi infancia.', example_pl: 'Mam dobre wspomnienia z dzieciństwa.' },
    { id: 351, spanish: 'recurso', polish: 'zasób', example_es: 'Los recursos naturales son limitados.', example_pl: 'Zasoby naturalne są ograniczone.' },
    { id: 352, spanish: 'red', polish: 'sieć', example_es: 'La red de internet es lenta.', example_pl: 'Sieć internetowa jest wolna.' },
    { id: 353, spanish: 'reforma', polish: 'reforma', example_es: 'La reforma educativa es necesaria.', example_pl: 'Reforma edukacji jest konieczna.' },
    { id: 354, spanish: 'régimen', polish: 'reżim, system', example_es: 'Es un régimen autoritario.', example_pl: 'To reżim autorytarny.' },
    { id: 355, spanish: 'reina', polish: 'królowa', example_es: 'La reina de España.', example_pl: 'Królowa Hiszpanii.' },
    { id: 356, spanish: 'respuesta', polish: 'odpowiedź', example_es: 'No sé la respuesta.', example_pl: 'Nie znam odpowiedzi.' },
    { id: 357, spanish: 'reunión', polish: 'spotkanie', example_es: 'Tengo una reunión a las diez.', example_pl: 'Mam spotkanie o dziesiątej.' },
    { id: 358, spanish: 'revista', polish: 'czasopismo', example_es: 'Leo una revista de moda.', example_pl: 'Czytam magazyn o modzie.' },
    { id: 359, spanish: 'riesgo', polish: 'ryzyko', example_es: 'No quiero correr el riesgo.', example_pl: 'Nie chcę podejmować ryzyka.' },
    { id: 360, spanish: 'salida', polish: 'wyjście', example_es: '¿Dónde está la salida?', example_pl: 'Gdzie jest wyjście?' },
    { id: 361, spanish: 'secretario', polish: 'sekretarz', example_es: 'El secretario general de la ONU.', example_pl: 'Sekretarz generalny ONZ.' },
    { id: 362, spanish: 'sector', polish: 'sektor', example_es: 'El sector de la tecnología está en auge.', example_pl: 'Sektor technologiczny przeżywa rozkwit.' },
    { id: 363, spanish: 'sensación', polish: 'uczucie', example_es: 'Tengo una sensación extraña.', example_pl: 'Mam dziwne uczucie.' },
    { id: 364, spanish: 'señal', polish: 'sygnał, znak', example_es: 'Es una buena señal.', example_pl: 'To dobry znak.' },
    { id: 365, spanish: 'silla', polish: 'krzesło', example_es: 'Siéntate en la silla.', example_pl: 'Usiądź na krześle.' },
    { id: 366, spanish: 'solución', polish: 'rozwiązanie', example_es: 'Buscamos una solución.', example_pl: 'Szukamy rozwiązania.' },
    { id: 367, spanish: 'sombra', polish: 'cień', example_es: 'Me siento en la sombra.', example_pl: 'Siedzę w cieniu.' },
    { id: 368, spanish: 'sonrisa', polish: 'uśmiech', example_es: 'Tiene una sonrisa bonita.', example_pl: 'Ona ma ładny uśmiech.' },
    { id: 369, spanish: 'sonido', polish: 'dźwięk', example_es: '¿Qué es ese sonido?', example_pl: 'Co to za dźwięk?' },
    { id: 370, spanish: 'tabla', polish: 'tabela, deska', example_es: 'Mira la tabla de precios.', example_pl: 'Spójrz na tabelę cen.' },
    { id: 371, spanish: 'tarde', polish: 'popołudnie, późno', example_es: 'Nos vemos por la tarde.', example_pl: 'Do zobaczenia po południu.' },
    { id: 372, spanish: 'teléfono', polish: 'telefon', example_es: 'Mi teléfono no funciona.', example_pl: 'Mój telefon nie działa.' },
    { id: 373, spanish: 'televisión', polish: 'telewizja', example_es: 'Veo la televisión por la noche.', example_pl: 'Oglądam telewizję wieczorem.' },
    { id: 374, spanish: 'texto', polish: 'tekst', example_es: 'Lee el texto en voz alta.', example_pl: 'Przeczytaj tekst na głos.' },
    { id: 375, spanish: 'título', polish: 'tytuł', example_es: '¿Cuál es el título del libro?', example_pl: 'Jaki jest tytuł tej książki?' },
    { id: 376, spanish: 'total', polish: 'całkowity, suma', example_es: 'El total es de 50 euros.', example_pl: 'Suma wynosi 50 euro.' },
    { id: 377, spanish: 'unidad', polish: 'jednostka', example_es: 'La familia es la unidad básica de la sociedad.', example_pl: 'Rodzina jest podstawową jednostką społeczeństwa.' },
    { id: 378, spanish: 'universidad', polish: 'uniwersytet', example_es: 'Estudio en la universidad.', example_pl: 'Studiuję na uniwersytecie.' },
    { id: 379, spanish: 'verano', polish: 'lato', example_es: 'Me gusta el verano.', example_pl: 'Lubię lato.' },
    { id: 380, spanish: 'versión', polish: 'wersja', example_es: 'Esta es la última versión del software.', example_pl: 'To jest najnowsza wersja oprogramowania.' },
    { id: 381, spanish: 'vestido', polish: 'sukienka', example_es: 'Lleva un vestido rojo.', example_pl: 'Ona ma na sobie czerwoną sukienkę.' },
    { id: 382, spanish: 'victoria', polish: 'zwycięstwo', example_es: 'Celebramos la victoria.', example_pl: 'Świętujemy zwycięstwo.' },
    { id: 383, spanish: 'violencia', polish: 'przemoc', example_es: 'Hay que detener la violencia.', example_pl: 'Trzeba powstrzymać przemoc.' },
    { id: 384, spanish: 'voluntad', polish: 'wola', example_es: 'Tiene una gran fuerza de voluntad.', example_pl: 'Ma wielką siłę woli.' },
    { id: 385, spanish: 'zapato', polish: 'but', example_es: 'Me compré unos zapatos nuevos.', example_pl: 'Kupiłem sobie nowe buty.' },
    { id: 386, spanish: 'final', polish: 'finał, końcowy', example_es: 'El final de la película fue sorprendente.', example_pl: 'Zakończenie filmu było zaskakujące.' },
    { id: 387, spanish: 'general', polish: 'generał, ogólny', example_es: 'En general, estoy de acuerdo.', example_pl: 'Ogólnie rzecz biorąc, zgadzam się.' },
    { id: 388, spanish: 'hospital', polish: 'szpital', example_es: 'Mi abuela está en el hospital.', example_pl: 'Moja babcia jest w szpitalu.' },
    { id: 389, spanish: 'ideal', polish: 'ideał, idealny', example_es: 'Es el lugar ideal para unas vacaciones.', example_pl: 'To idealne miejsce na wakacje.' },
    { id: 390, spanish: 'igual', polish: 'równy, taki sam', example_es: 'Somos todos iguales.', example_pl: 'Wszyscy jesteśmy równi.' },
    { id: 391, spanish: 'joven', polish: 'młody', example_es: 'Es un artista muy joven.', example_pl: 'To bardzo młody artysta.' },
    { id: 392, spanish: 'local', polish: 'lokalny', example_es: 'Prefiero comprar productos locales.', example_pl: 'Wolę kupować lokalne produkty.' },
    { id: 393, spanish: 'mal', polish: 'zły', example_es: 'Me siento mal.', example_pl: 'Źle się czuję.' },
    { id: 394, spanish: 'mayor', polish: 'większy, starszy', example_es: 'Mi hermano es mayor que yo.', example_pl: 'Mój brat jest starszy ode mnie.' },
    { id: 395, spanish: 'menor', polish: 'mniejszy, młodszy', example_es: 'Es el menor de la clase.', example_pl: 'On jest najmłodszy w klasie.' },
    { id: 396, spanish: 'militar', polish: 'wojskowy', example_es: 'Tiene una carrera militar.', example_pl: 'Ma karierę wojskową.' },
    { id: 397, spanish: 'moral', polish: 'moralny', example_es: 'Es una cuestión moral.', example_pl: 'To kwestia moralna.' },
    { id: 398, spanish: 'mundial', polish: 'światowy', example_es: 'La Segunda Guerra Mundial.', example_pl: 'Druga Wojna Światowa.' },
    { id: 399, spanish: 'nacional', polish: 'narodowy', example_es: 'El himno nacional.', example_pl: 'Hymn narodowy.' },
    { id: 400, spanish: 'natural', polish: 'naturalny', example_es: 'Es un producto cien por cien natural.', example_pl: 'To produkt w stu procentach naturalny.' },
    { id: 401, spanish: 'negro', polish: 'czarny', example_es: 'Tengo un gato negro.', example_pl: 'Mam czarnego kota.' },
    { id: 402, spanish: 'nuevo', polish: 'nowy', example_es: 'Este es mi coche nuevo.', example_pl: 'To jest mój nowy samochód.' },
    { id: 403, spanish: 'oficial', polish: 'oficjalny', example_es: 'Es la versión oficial.', example_pl: 'To jest oficjalna wersja.' },
    { id: 404, spanish: 'personal', polish: 'osobisty', example_es: 'Es un asunto personal.', example_pl: 'To sprawa osobista.' },
    { id: 405, spanish: 'pleno', polish: 'pełny', example_es: 'Estamos en pleno verano.', example_pl: 'Jesteśmy w pełni lata.' },
    { id: 406, spanish: 'político', polish: 'polityczny', example_es: 'Es un líder político.', example_pl: 'To lider polityczny.' },
    { id: 407, spanish: 'posible', polish: 'możliwy', example_es: 'Todo es posible.', example_pl: 'Wszystko jest możliwe.' },
    { id: 408, spanish: 'principal', polish: 'główny', example_es: 'La calle principal.', example_pl: 'Główna ulica.' },
    { id: 409, spanish: 'profesional', polish: 'profesjonalny', example_es: 'Es un jugador profesional.', example_pl: 'To profesjonalny gracz.' },
    { id: 410, spanish: 'propio', polish: 'własny', example_es: 'Tengo mi propio negocio.', example_pl: 'Mam własny biznes.' },
    { id: 411, spanish: 'próximo', polish: 'następny', example_es: 'La próxima semana.', example_pl: 'W przyszłym tygodniu.' },
    { id: 412, spanish: 'público', polish: 'publiczny', example_es: 'El transporte público.', example_pl: 'Transport publiczny.' },
    { id: 413, spanish: 'puro', polish: 'czysty', example_es: 'Aire puro.', example_pl: 'Czyste powietrze.' },
    { id: 414, spanish: 'raro', polish: 'dziwny', example_es: 'Es un poco raro.', example_pl: 'To trochę dziwne.' },
    { id: 415, spanish: 'real', polish: 'prawdziwy, królewski', example_es: 'El palacio real.', example_pl: 'Pałac królewski.' },
    { id: 416, spanish: 'rojo', polish: 'czerwony', example_es: 'El coche es rojo.', example_pl: 'Samochód jest czerwony.' },
    { id: 417, spanish: 'santo', polish: 'święty', example_es: 'El Santo Padre.', example_pl: 'Ojciec Święty.' },
    { id: 418, spanish: 'seguro', polish: 'pewny', example_es: '¿Estás seguro?', example_pl: 'Jesteś pewien?' },
    { id: 419, spanish: 'serio', polish: 'poważny', example_es: 'Es un problema serio.', example_pl: 'To poważny problem.' },
    { id: 420, spanish: 'simple', polish: 'prosty', example_es: 'La respuesta es simple.', example_pl: 'Odpowiedź jest prosta.' },
    { id: 421, spanish: 'social', polish: 'społeczny', example_es: 'Las redes sociales.', example_pl: 'Media społecznościowe.' },
    { id: 422, spanish: 'solo', polish: 'sam', example_es: 'Estoy solo en casa.', example_pl: 'Jestem sam w domu.' },
    { id: 423, spanish: 'superior', polish: 'wyższy', example_es: 'La educación superior.', example_pl: 'Szkolnictwo wyższe.' },
    { id: 424, spanish: 'técnico', polish: 'techniczny', example_es: 'Un problema técnico.', example_pl: 'Problem techniczny.' },
    { id: 425, spanish: 'tercero', polish: 'trzeci', example_es: 'El tercer piso.', example_pl: 'Trzecie piętro.' },
    { id: 426, spanish: 'tradicional', polish: 'tradycyjny', example_es: 'La comida tradicional.', example_pl: 'Tradycyjne jedzenie.' },
    { id: 427, spanish: 'tranquilo', polish: 'spokojny', example_es: 'Es un lugar tranquilo.', example_pl: 'To spokojne miejsce.' },
    { id: 428, spanish: 'triste', polish: 'smutny', example_es: 'Estoy un poco triste.', example_pl: 'Jestem trochę smutny.' },
    { id: 429, spanish: 'último', polish: 'ostatni', example_es: 'Es la última vez.', example_pl: 'To ostatni raz.' },
    { id: 430, spanish: 'único', polish: 'jedyny', example_es: 'Es mi único amigo.', example_pl: 'To mój jedyny przyjaciel.' },
    { id: 431, spanish: 'urbano', polish: 'miejski', example_es: 'El transporte urbano.', example_pl: 'Transport miejski.' },
    { id: 432, spanish: 'útil', polish: 'użyteczny', example_es: 'Esta herramienta es muy útil.', example_pl: 'To narzędzie jest bardzo użyteczne.' },
    { id: 433, spanish: 'vacío', polish: 'pusty', example_es: 'El vaso está vacío.', example_pl: 'Szklanka jest pusta.' },
    { id: 434, spanish: 'varios', polish: 'kilka', example_es: 'Tengo varios libros.', example_pl: 'Mam kilka książek.' },
    { id: 435, spanish: 'verde', polish: 'zielony', example_es: 'La hierba es verde.', example_pl: 'Trawa jest zielona.' },
    { id: 436, spanish: 'viejo', polish: 'stary', example_es: 'Es un coche viejo.', example_pl: 'To stary samochód.' },
    { id: 437, spanish: 'vivo', polish: 'żywy', example_es: 'El pez está vivo.', example_pl: 'Ryba jest żywa.' },
    { id: 438, spanish: 'abrir', polish: 'otwierać', example_es: 'Abre la puerta.', example_pl: 'Otwórz drzwi.' },
    { id: 439, spanish: 'acabar', polish: 'kończyć', example_es: 'Acabo de llegar.', example_pl: 'Właśnie przyjechałem.' },
    { id: 440, spanish: 'aceptar', polish: 'akceptować', example_es: 'Acepto tus disculpas.', example_pl: 'Akceptuję twoje przeprosiny.' },
    { id: 441, spanish: 'alcanzar', polish: 'osiągać', example_es: 'Alcancé mis objetivos.', example_pl: 'Osiągnąłem swoje cele.' },
    { id: 442, spanish: 'aparecer', polish: 'pojawiać się', example_es: 'El sol apareció.', example_pl: 'Pojawiło się słońce.' },
    { id: 443, spanish: 'ayudar', polish: 'pomagać', example_es: '¿Te puedo ayudar?', example_pl: 'Mogę ci pomóc?' },
    { id: 444, spanish: 'buscar', polish: 'szukać', example_es: 'Busco mis llaves.', example_pl: 'Szukam moich kluczy.' },
    { id: 445, spanish: 'caer', polish: 'upadać', example_es: 'Las hojas caen en otoño.', example_pl: 'Liście opadają jesienią.' },
    { id: 446, spanish: 'cambiar', polish: 'zmieniać', example_es: 'Quiero cambiar de trabajo.', example_pl: 'Chcę zmienić pracę.' },
    { id: 447, spanish: 'comenzar', polish: 'zaczynać', example_es: 'La clase comienza a las nueve.', example_pl: 'Lekcja zaczyna się o dziewiątej.' },
    { id: 448, spanish: 'comprender', polish: 'rozumieć', example_es: 'No comprendo la pregunta.', example_pl: 'Nie rozumiem pytania.' },
    { id: 449, spanish: 'conocer', polish: 'znać', example_es: 'No conozco a esa persona.', example_pl: 'Nie znam tej osoby.' },
    { id: 450, spanish: 'conseguir', polish: 'zdobywać', example_es: 'Conseguí el trabajo.', example_pl: 'Dostałem tę pracę.' },
    { id: 451, spanish: 'considerar', polish: 'rozważać', example_es: 'Debes considerar todas las opciones.', example_pl: 'Musisz rozważyć wszystkie opcje.' },
    { id: 452, spanish: 'contar', polish: 'liczyć, opowiadać', example_es: 'Cuéntame una historia.', example_pl: 'Opowiedz mi historię.' },
    { id: 453, spanish: 'contener', polish: 'zawierać', example_es: 'La caja contiene libros.', example_pl: 'Pudełko zawiera książki.' },
    { id: 454, spanish: 'contestar', polish: 'odpowiadać', example_es: 'Contesta el teléfono.', example_pl: 'Odbierz telefon.' },
    { id: 455, spanish: 'continuar', polish: 'kontynuować', example_es: 'Debemos continuar.', example_pl: 'Musimy kontynuować.' },
    { id: 456, spanish: 'convertir', polish: 'zmieniać', example_es: 'El agua se convierte en hielo.', example_pl: 'Woda zamienia się w lód.' },
    { id: 457, spanish: 'correr', polish: 'biec', example_es: 'Me gusta correr por la mañana.', example_pl: 'Lubię biegać rano.' },
    { id: 458, spanish: 'crear', polish: 'tworzyć', example_es: 'El artista crea una escultura.', example_pl: 'Artysta tworzy rzeźbę.' },
    { id: 459, spanish: 'crecer', polish: 'rosnąć', example_es: 'Las plantas crecen con el sol.', example_pl: 'Rośliny rosną dzięki słońcu.' },
    { id: 460, spanish: 'creer', polish: 'wierzyć', example_es: 'Creo en ti.', example_pl: 'Wierzę w ciebie.' },
    { id: 461, spanish: 'cruzar', polish: 'przechodzić', example_es: 'Cruza la calle con cuidado.', example_pl: 'Przechodź przez ulicę ostrożnie.' },
    { id: 462, spanish: 'cubrir', polish: 'przykrywać', example_es: 'Cubre la comida.', example_pl: 'Przykryj jedzenie.' },
    { id: 463, spanish: 'cumplir', polish: 'kończyć (lata), spełniać', example_es: 'Mañana cumplo 30 años.', example_pl: 'Jutro kończę 30 lat.' },
    { id: 464, spanish: 'deber', polish: 'musieć', example_es: 'Debo estudiar más.', example_pl: 'Muszę więcej się uczyć.' },
    { id: 465, spanish: 'decidir', polish: 'decydować', example_es: 'No puedo decidir.', example_pl: 'Nie mogę się zdecydować.' },
    { id: 466, spanish: 'dejar', polish: 'zostawiać', example_es: 'Deja las llaves en la mesa.', example_pl: 'Zostaw klucze na stole.' },
    { id: 467, spanish: 'demostrar', polish: 'udowadniać', example_es: 'Voy a demostrar que tengo razón.', example_pl: 'Udowodnię, że mam rację.' },
    { id: 468, spanish: 'descansar', polish: 'odpoczywać', example_es: 'Necesito descansar.', example_pl: 'Muszę odpocząć.' },
    { id: 469, spanish: 'descubrir', polish: 'odkrywać', example_es: 'Descubrieron una nueva especie.', example_pl: 'Odkryli nowy gatunek.' },
    { id: 470, spanish: 'desear', polish: 'życzyć', example_es: 'Te deseo lo mejor.', example_pl: 'Życzę ci wszystkiego najlepszego.' },
    { id: 471, spanish: 'dirigir', polish: 'kierować', example_es: 'Dirige una gran empresa.', example_pl: 'On kieruje dużą firmą.' },
    { id: 472, spanish: 'discutir', polish: 'kłócić się', example_es: 'No me gusta discutir.', example_pl: 'Nie lubię się kłócić.' },
    { id: 473, spanish: 'dormir', polish: 'spać', example_es: 'Duermo ocho horas al día.', example_pl: 'Śpię osiem godzin dziennie.' },
    { id: 474, spanish: 'dudar', polish: 'wątpić', example_es: 'Dudo que sea verdad.', example_pl: 'Wątpię, żeby to była prawda.' },
    { id: 475, spanish: 'echar', polish: 'rzucać', example_es: 'Echa la carta al buzón.', example_pl: 'Wrzuc list do skrzynki.' },
    { id: 476, spanish: 'elegir', polish: 'wybierać', example_es: 'Elige un color.', example_pl: 'Wybierz kolor.' },
    { id: 477, spanish: 'empezar', polish: 'zaczynać', example_es: 'Voy a empezar a estudiar.', example_pl: 'Zaczynam się uczyć.' },
    { id: 478, spanish: 'encontrar', polish: 'znajdować', example_es: 'No encuentro mis gafas.', example_pl: 'Nie mogę znaleźć moich okularów.' },
    { id: 479, spanish: 'enseñar', polish: 'uczyć', example_es: 'Mi padre me enseñó a conducir.', example_pl: 'Mój ojciec nauczył mnie jeździć samochodem.' },
    { id: 480, spanish: 'entender', polish: 'rozumieć', example_es: 'No entiendo nada.', example_pl: 'Nic nie rozumiem.' },
    { id: 481, spanish: 'entrar', polish: 'wchodzić', example_es: 'Puedes entrar.', example_pl: 'Możesz wejść.' },
    { id: 482, spanish: 'enviar', polish: 'wysyłać', example_es: 'Voy a enviar un correo electrónico.', example_pl: 'Wyślę e-maila.' },
    { id: 483, spanish: 'escribir', polish: 'pisać', example_es: 'Escribo un libro.', example_pl: 'Piszę książkę.' },
    { id: 484, spanish: 'escuchar', polish: 'słuchać', example_es: 'Escucho música.', example_pl: 'Słucham muzyki.' },
    { id: 485, spanish: 'esperar', polish: 'czekać, mieć nadzieję', example_es: 'Espero el autobús.', example_pl: 'Czekam na autobus.' },
    { id: 486, spanish: 'estudiar', polish: 'uczyć się', example_es: 'Estudio para el examen.', example_pl: 'Uczę się do egzaminu.' },
    { id: 487, spanish: 'evitar', polish: 'unikać', example_es: 'Intenta evitar los problemas.', example_pl: 'Staraj się unikać problemów.' },
    { id: 488, spanish: 'existir', polish: 'istnieć', example_es: 'Los fantasmas no existen.', example_pl: 'Duchy nie istnieją.' },
    { id: 489, spanish: 'explicar', polish: 'tłumaczyć', example_es: '¿Me lo puedes explicar?', example_pl: 'Możesz mi to wytłumaczyć?' },
    { id: 490, spanish: 'expresar', polish: 'wyrażać', example_es: 'Expresa tus sentimientos.', example_pl: 'Wyraź swoje uczucia.' },
    { id: 491, spanish: 'faltar', polish: 'brakować', example_es: 'Me falta un euro.', example_pl: 'Brakuje mi jednego euro.' },
    { id: 492, spanish: 'fijar', polish: 'ustalać', example_es: 'Fijamos una fecha para la reunión.', example_pl: 'Ustaliliśmy datę spotkania.' },
    { id: 493, spanish: 'formar', polish: 'formować', example_es: 'Formamos un círculo.', example_pl: 'Tworzymy koło.' },
    { id: 494, spanish: 'ganar', polish: 'wygrywać, zarabiać', example_es: 'Ganamos el partido.', example_pl: 'Wygraliśmy mecz.' },
    { id: 495, spanish: 'gastar', polish: 'wydawać', example_es: 'No gastes tanto dinero.', example_pl: 'Nie wydawaj tyle pieniędzy.' },
    { id: 496, spanish: 'gritar', polish: 'krzyczeć', example_es: 'No me grites.', example_pl: 'Nie krzycz na mnie.' },
    { id: 497, spanish: 'guardar', polish: 'przechowywać, zachować', example_es: 'Guarda el secreto.', example_pl: 'Zachowaj tajemnicę.' },
    { id: 498, spanish: 'gustar', polish: 'lubić', example_es: 'Me gusta el chocolate.', example_pl: 'Lubię czekoladę.' },
    { id: 499, spanish: 'hablar', polish: 'mówić', example_es: 'Hablo español.', example_pl: 'Mówię po hiszpańsku.' },
    { id: 500, spanish: 'hallar', polish: 'znajdować', example_es: 'Hallaron un tesoro.', example_pl: 'Znaleźli skarb.' },
    { id: 501, spanish: 'imaginar', polish: 'wyobrażać sobie', example_es: 'Imagina un mundo sin guerras.', example_pl: 'Wyobraź sobie świat bez wojen.' },
    { id: 502, spanish: 'importar', polish: 'mieć znaczenie, importować', example_es: 'No me importa.', example_pl: 'Nie obchodzi mnie to.' },
    { id: 503, spanish: 'incluir', polish: 'zawierać', example_es: 'El precio incluye el desayuno.', example_pl: 'Cena zawiera śniadanie.' },
    { id: 504, spanish: 'indicar', polish: 'wskazywać', example_es: 'La señal indica la dirección.', example_pl: 'Znak wskazuje kierunek.' },
    { id: 505, spanish: 'informar', polish: 'informować', example_es: 'Me informaron de la situación.', example_pl: 'Poinformowali mnie o sytuacji.' },
    { id: 506, spanish: 'intentar', polish: 'próbować', example_es: 'Voy a intentar hacerlo.', example_pl: 'Spróbuję to zrobić.' },
    { id: 507, spanish: 'interesar', polish: 'interesować', example_es: 'Me interesa la historia.', example_pl: 'Interesuje mnie historia.' },
    { id: 508, spanish: 'invitar', polish: 'zapraszać', example_es: 'Te invito a mi fiesta.', example_pl: 'Zapraszam cię na moją imprezę.' },
    { id: 509, spanish: 'jugar', polish: 'grać', example_es: 'Juego al tenis.', example_pl: 'Gram w tenisa.' },
    { id: 510, spanish: 'juntar', polish: 'łączyć', example_es: 'Juntamos las mesas.', example_pl: 'Połączyliśmy stoły.' },
    { id: 511, spanish: 'lanzar', polish: 'rzucać', example_es: 'Lanza la pelota.', example_pl: 'Rzuć piłkę.' },
    { id: 512, spanish: 'lavar', polish: 'myć', example_es: 'Lávate las manos.', example_pl: 'Umyj ręce.' },
    { id: 513, spanish: 'leer', polish: 'czytać', example_es: 'Me gusta leer novelas.', example_pl: 'Lubię czytać powieści.' },
    { id: 514, spanish: 'levantar', polish: 'podnosić', example_es: 'Levanta la mano.', example_pl: 'Podnieś rękę.' },
    { id: 515, spanish: 'llamar', polish: 'dzwonić, nazywać', example_es: 'Te llamo más tarde.', example_pl: 'Zadzwonię do ciebie później.' },
    { id: 516, spanish: 'llegar', polish: 'przyjeżdżać', example_es: 'Llego a las cinco.', example_pl: 'Przyjeżdżam o piątej.' },
    { id: 517, spanish: 'llenar', polish: 'napełniać', example_es: 'Llena el vaso de agua.', example_pl: 'Napełnij szklankę wodą.' },
    { id: 518, spanish: 'llevar', polish: 'nosić, zabierać', example_es: 'Llevo una camiseta azul.', example_pl: 'Mam na sobie niebieską koszulkę.' },
    { id: 519, spanish: 'lograr', polish: 'osiągać', example_es: 'Logré mi objetivo.', example_pl: 'Osiągnąłem swój cel.' },
    { id: 520, spanish: 'luchar', polish: 'walczyć', example_es: 'Lucha por tus sueños.', example_pl: 'Walcz o swoje marzenia.' },
    { id: 521, spanish: 'mandar', polish: 'wysyłać, rozkazywać', example_es: 'Manda un mensaje.', example_pl: 'Wyślij wiadomość.' },
    { id: 522, spanish: 'mantener', polish: 'utrzymywać', example_es: 'Mantén la calma.', example_pl: 'Zachowaj spokój.' },
    { id: 523, spanish: 'marcar', polish: 'zaznaczać', example_es: 'Marca la respuesta correcta.', example_pl: 'Zaznacz poprawną odpowiedź.' },
    { id: 524, spanish: 'matar', polish: 'zabijać', example_es: 'No mates a los animales.', example_pl: 'Nie zabijaj zwierząt.' },
    { id: 525, spanish: 'meter', polish: 'wkładać', example_es: 'Mete la ropa en el armario.', example_pl: 'Włóż ubrania do szafy.' },
    { id: 526, spanish: 'mirar', polish: 'patrzeć', example_es: 'Mira esa película.', example_pl: 'Obejrzyj ten film.' },
    { id: 527, spanish: 'morir', polish: 'umierać', example_es: 'Todos vamos a morir algún día.', example_pl: 'Wszyscy kiedyś umrzemy.' },
    { id: 528, spanish: 'mostrar', polish: 'pokazywać', example_es: 'Muéstrame el camino.', example_pl: 'Pokaż mi drogę.' },
    { id: 529, spanish: 'mover', polish: 'ruszać', example_es: 'Mueve la silla.', example_pl: 'Przesuń krzesło.' },
    { id: 530, spanish: 'nacer', polish: 'rodzić się', example_es: 'Nací en Polonia.', example_pl: 'Urodziłem się w Polsce.' },
    { id: 531, spanish: 'necesitar', polish: 'potrzebować', example_es: 'Necesito ayuda.', example_pl: 'Potrzebuję pomocy.' },
    { id: 532, spanish: 'negar', polish: 'zaprzeczać', example_es: 'Lo negó todo.', example_pl: 'Wszystkiemu zaprzeczył.' },
    { id: 533, spanish: 'notar', polish: 'zauważać', example_es: 'Noté un cambio en su actitud.', example_pl: 'Zauważyłem zmianę w jego postawie.' },
    { id: 534, spanish: 'obtener', polish: 'otrzymywać', example_es: 'Obtuve un buen resultado.', example_pl: 'Otrzymałem dobry wynik.' },
    { id: 535, spanish: 'ocurrir', polish: 'wydarzać się', example_es: '¿Qué ocurrió?', example_pl: 'Co się wydarzyło?' },
    { id: 536, spanish: 'ofrecer', polish: 'oferować', example_es: 'Te ofrezco mi ayuda.', example_pl: 'Oferuję ci moją pomoc.' },
    { id: 537, spanish: 'oír', polish: 'słyszeć', example_es: 'No oigo nada.', example_pl: 'Nic nie słyszę.' },
    { id: 538, spanish: 'olvidar', polish: 'zapominać', example_es: 'No olvides las llaves.', example_pl: 'Nie zapomnij kluczy.' },
    { id: 539, spanish: 'pagar', polish: 'płacić', example_es: 'Voy a pagar la cuenta.', example_pl: 'Zapłacę rachunek.' },
    { id: 540, spanish: 'parar', polish: 'zatrzymywać się', example_es: 'Para el coche.', example_pl: 'Zatrzymaj samochód.' },
    { id: 541, spanish: 'parecer', polish: 'wydawać się', example_es: 'Parece una buena idea.', example_pl: 'To wydaje się dobrym pomysłem.' },
    { id: 542, spanish: 'partir', polish: 'dzielić, wyjeżdżać', example_es: 'Partimos mañana.', example_pl: 'Wyjeżdżamy jutro.' },
    { id: 543, spanish: 'pasar', polish: 'przechodzić, dziać się', example_es: '¿Qué pasa?', example_pl: 'Co się dzieje?' },
    { id: 544, spanish: 'pedir', polish: 'prosić', example_es: 'Pido un favor.', example_pl: 'Proszę o przysługę.' },
    { id: 545, spanish: 'pensar', polish: 'myśleć', example_es: 'Pienso en ti.', example_pl: 'Myślę o tobie.' },
    { id: 546, spanish: 'perder', polish: 'tracić', example_es: 'No quiero perder el tren.', example_pl: 'Nie chcę spóźnić się na pociąg.' },
    { id: 547, spanish: 'permitir', polish: 'pozwalać', example_es: 'No se permite fumar.', example_pl: 'Palenie jest zabronione.' },
    { id: 548, spanish: 'pintar', polish: 'malować', example_es: 'Pinto un cuadro.', example_pl: 'Maluję obraz.' },
    { id: 549, spanish: 'poder', polish: 'móc', example_es: 'Puedes hacerlo.', example_pl: 'Możesz to zrobić.' },
    { id: 550, spanish: 'poner', polish: 'kłaść', example_es: 'Pon el libro en la mesa.', example_pl: 'Połóż książkę na stole.' },
    { id: 451, spanish: 'considerar', polish: 'rozważać', example_es: 'Debes considerar todas las opciones.', example_pl: 'Musisz rozważyć wszystkie opcje.' },
    { id: 452, spanish: 'contar', polish: 'liczyć, opowiadać', example_es: 'Cuéntame una historia.', example_pl: 'Opowiedz mi historię.' },
    { id: 453, spanish: 'contener', polish: 'zawierać', example_es: 'La caja contiene libros.', example_pl: 'Pudełko zawiera książki.' },
    { id: 454, spanish: 'contestar', polish: 'odpowiadać', example_es: 'Contesta el teléfono.', example_pl: 'Odbierz telefon.' },
    { id: 455, spanish: 'continuar', polish: 'kontynuować', example_es: 'Debemos continuar.', example_pl: 'Musimy kontynuować.' },
    { id: 456, spanish: 'convertir', polish: 'zmieniać', example_es: 'El agua se convierte en hielo.', example_pl: 'Woda zamienia się w lód.' },
    { id: 457, spanish: 'correr', polish: 'biec', example_es: 'Me gusta correr por la mañana.', example_pl: 'Lubię biegać rano.' },
    { id: 458, spanish: 'crear', polish: 'tworzyć', example_es: 'El artista crea una escultura.', example_pl: 'Artysta tworzy rzeźbę.' },
    { id: 459, spanish: 'crecer', polish: 'rosnąć', example_es: 'Las plantas crecen con el sol.', example_pl: 'Rośliny rosną dzięki słońcu.' },
    { id: 460, spanish: 'creer', polish: 'wierzyć', example_es: 'Creo en ti.', example_pl: 'Wierzę w ciebie.' },
    { id: 461, spanish: 'cruzar', polish: 'przechodzić', example_es: 'Cruza la calle con cuidado.', example_pl: 'Przechodź przez ulicę ostrożnie.' },
    { id: 462, spanish: 'cubrir', polish: 'przykrywać', example_es: 'Cubre la comida.', example_pl: 'Przykryj jedzenie.' },
    { id: 463, spanish: 'cumplir', polish: 'kończyć (lata), spełniać', example_es: 'Mañana cumplo 30 años.', example_pl: 'Jutro kończę 30 lat.' },
    { id: 464, spanish: 'deber', polish: 'musieć', example_es: 'Debo estudiar más.', example_pl: 'Muszę więcej się uczyć.' },
    { id: 465, spanish: 'decidir', polish: 'decydować', example_es: 'No puedo decidir.', example_pl: 'Nie mogę się zdecydować.' },
    { id: 466, spanish: 'dejar', polish: 'zostawiać', example_es: 'Deja las llaves en la mesa.', example_pl: 'Zostaw klucze na stole.' },
    { id: 467, spanish: 'demostrar', polish: 'udowadniać', example_es: 'Voy a demostrar que tengo razón.', example_pl: 'Udowodnię, że mam rację.' },
    { id: 468, spanish: 'descansar', polish: 'odpoczywać', example_es: 'Necesito descansar.', example_pl: 'Muszę odpocząć.' },
    { id: 469, spanish: 'descubrir', polish: 'odkrywać', example_es: 'Descubrieron una nueva especie.', example_pl: 'Odkryli nowy gatunek.' },
    { id: 470, spanish: 'desear', polish: 'życzyć', example_es: 'Te deseo lo mejor.', example_pl: 'Życzę ci wszystkiego najlepszego.' },
    { id: 471, spanish: 'dirigir', polish: 'kierować', example_es: 'Dirige una gran empresa.', example_pl: 'On kieruje dużą firmą.' },
    { id: 472, spanish: 'discutir', polish: 'kłócić się', example_es: 'No me gusta discutir.', example_pl: 'Nie lubię się kłócić.' },
    { id: 473, spanish: 'dormir', polish: 'spać', example_es: 'Duermo ocho horas al día.', example_pl: 'Śpię osiem godzin dziennie.' },
    { id: 474, spanish: 'dudar', polish: 'wątpić', example_es: 'Dudo que sea verdad.', example_pl: 'Wątpię, żeby to była prawda.' },
    { id: 475, spanish: 'echar', polish: 'rzucać', example_es: 'Echa la carta al buzón.', example_pl: 'Wrzuc list do skrzynki.' },
    { id: 476, spanish: 'elegir', polish: 'wybierać', example_es: 'Elige un color.', example_pl: 'Wybierz kolor.' },
    { id: 477, spanish: 'empezar', polish: 'zaczynać', example_es: 'Voy a empezar a estudiar.', example_pl: 'Zaczynam się uczyć.' },
    { id: 478, spanish: 'encontrar', polish: 'znajdować', example_es: 'No encuentro mis gafas.', example_pl: 'Nie mogę znaleźć moich okularów.' },
    { id: 479, spanish: 'enseñar', polish: 'uczyć', example_es: 'Mi padre me enseñó a conducir.', example_pl: 'Mój ojciec nauczył mnie jeździć samochodem.' },
    { id: 480, spanish: 'entender', polish: 'rozumieć', example_es: 'No entiendo nada.', example_pl: 'Nic nie rozumiem.' },
    { id: 481, spanish: 'entrar', polish: 'wchodzić', example_es: 'Puedes entrar.', example_pl: 'Możesz wejść.' },
    { id: 482, spanish: 'enviar', polish: 'wysyłać', example_es: 'Voy a enviar un correo electrónico.', example_pl: 'Wyślę e-maila.' },
    { id: 483, spanish: 'escribir', polish: 'pisać', example_es: 'Escribo un libro.', example_pl: 'Piszę książkę.' },
    { id: 484, spanish: 'escuchar', polish: 'słuchać', example_es: 'Escucho música.', example_pl: 'Słucham muzyki.' },
    { id: 485, spanish: 'esperar', polish: 'czekać, mieć nadzieję', example_es: 'Espero el autobús.', example_pl: 'Czekam na autobus.' },
    { id: 486, spanish: 'estudiar', polish: 'uczyć się', example_es: 'Estudio para el examen.', example_pl: 'Uczę się do egzaminu.' },
    { id: 487, spanish: 'evitar', polish: 'unikać', example_es: 'Intenta evitar los problemas.', example_pl: 'Staraj się unikać problemów.' },
    { id: 488, spanish: 'existir', polish: 'istnieć', example_es: 'Los fantasmas no existen.', example_pl: 'Duchy nie istnieją.' },
    { id: 489, spanish: 'explicar', polish: 'tłumaczyć', example_es: '¿Me lo puedes explicar?', example_pl: 'Możesz mi to wytłumaczyć?' },
    { id: 490, spanish: 'expresar', polish: 'wyrażać', example_es: 'Expresa tus sentimientos.', example_pl: 'Wyraź swoje uczucia.' },
    { id: 491, spanish: 'faltar', polish: 'brakować', example_es: 'Me falta un euro.', example_pl: 'Brakuje mi jednego euro.' },
    { id: 492, spanish: 'fijar', polish: 'ustalać', example_es: 'Fijamos una fecha para la reunión.', example_pl: 'Ustaliliśmy datę spotkania.' },
    { id: 493, spanish: 'formar', polish: 'formować', example_es: 'Formamos un círculo.', example_pl: 'Tworzymy koło.' },
    { id: 494, spanish: 'ganar', polish: 'wygrywać, zarabiać', example_es: 'Ganamos el partido.', example_pl: 'Wygraliśmy mecz.' },
    { id: 495, spanish: 'gastar', polish: 'wydawać', example_es: 'No gastes tanto dinero.', example_pl: 'Nie wydawaj tyle pieniędzy.' },
    { id: 496, spanish: 'gritar', polish: 'krzyczeć', example_es: 'No me grites.', example_pl: 'Nie krzycz na mnie.' },
    { id: 497, spanish: 'guardar', polish: 'przechowywać, zachować', example_es: 'Guarda el secreto.', example_pl: 'Zachowaj tajemnicę.' },
    { id: 498, spanish: 'gustar', polish: 'lubić', example_es: 'Me gusta el chocolate.', example_pl: 'Lubię czekoladę.' },
    { id: 499, spanish: 'hablar', polish: 'mówić', example_es: 'Hablo español.', example_pl: 'Mówię po hiszpańsku.' },
    { id: 500, spanish: 'hallar', polish: 'znajdować', example_es: 'Hallaron un tesoro.', example_pl: 'Znaleźli skarb.' },
    { id: 501, spanish: 'imaginar', polish: 'wyobrażać sobie', example_es: 'Imagina un mundo sin guerras.', example_pl: 'Wyobraź sobie świat bez wojen.' },
    { id: 502, spanish: 'importar', polish: 'mieć znaczenie, importować', example_es: 'No me importa.', example_pl: 'Nie obchodzi mnie to.' },
    { id: 503, spanish: 'incluir', polish: 'zawierać', example_es: 'El precio incluye el desayuno.', example_pl: 'Cena zawiera śniadanie.' },
    { id: 504, spanish: 'indicar', polish: 'wskazywać', example_es: 'La señal indica la dirección.', example_pl: 'Znak wskazuje kierunek.' },
    { id: 505, spanish: 'informar', polish: 'informować', example_es: 'Me informaron de la situación.', example_pl: 'Poinformowali mnie o sytuacji.' },
    { id: 506, spanish: 'intentar', polish: 'próbować', example_es: 'Voy a intentar hacerlo.', example_pl: 'Spróbuję to zrobić.' },
    { id: 507, spanish: 'interesar', polish: 'interesować', example_es: 'Me interesa la historia.', example_pl: 'Interesuje mnie historia.' },
    { id: 508, spanish: 'invitar', polish: 'zapraszać', example_es: 'Te invito a mi fiesta.', example_pl: 'Zapraszam cię na moją imprezę.' },
    { id: 509, spanish: 'jugar', polish: 'grać', example_es: 'Juego al tenis.', example_pl: 'Gram w tenisa.' },
    { id: 510, spanish: 'juntar', polish: 'łączyć', example_es: 'Juntamos las mesas.', example_pl: 'Połączyliśmy stoły.' },
    { id: 511, spanish: 'lanzar', polish: 'rzucać', example_es: 'Lanza la pelota.', example_pl: 'Rzuć piłkę.' },
    { id: 512, spanish: 'lavar', polish: 'myć', example_es: 'Lávate las manos.', example_pl: 'Umyj ręce.' },
    { id: 513, spanish: 'leer', polish: 'czytać', example_es: 'Me gusta leer novelas.', example_pl: 'Lubię czytać powieści.' },
    { id: 514, spanish: 'levantar', polish: 'podnosić', example_es: 'Levanta la mano.', example_pl: 'Podnieś rękę.' },
    { id: 515, spanish: 'llamar', polish: 'dzwonić, nazywać', example_es: 'Te llamo más tarde.', example_pl: 'Zadzwonię do ciebie później.' },
    { id: 516, spanish: 'llegar', polish: 'przyjeżdżać', example_es: 'Llego a las cinco.', example_pl: 'Przyjeżdżam o piątej.' },
    { id: 517, spanish: 'llenar', polish: 'napełniać', example_es: 'Llena el vaso de agua.', example_pl: 'Napełnij szklankę wodą.' },
    { id: 518, spanish: 'llevar', polish: 'nosić, zabierać', example_es: 'Llevo una camiseta azul.', example_pl: 'Mam na sobie niebieską koszulkę.' },
    { id: 519, spanish: 'lograr', polish: 'osiągać', example_es: 'Logré mi objetivo.', example_pl: 'Osiągnąłem swój cel.' },
    { id: 520, spanish: 'luchar', polish: 'walczyć', example_es: 'Lucha por tus sueños.', example_pl: 'Walcz o swoje marzenia.' },
    { id: 521, spanish: 'mandar', polish: 'wysyłać, rozkazywać', example_es: 'Manda un mensaje.', example_pl: 'Wyślij wiadomość.' },
    { id: 522, spanish: 'mantener', polish: 'utrzymywać', example_es: 'Mantén la calma.', example_pl: 'Zachowaj spokój.' },
    { id: 523, spanish: 'marcar', polish: 'zaznaczać', example_es: 'Marca la respuesta correcta.', example_pl: 'Zaznacz poprawną odpowiedź.' },
    { id: 524, spanish: 'matar', polish: 'zabijać', example_es: 'No mates a los animales.', example_pl: 'Nie zabijaj zwierząt.' },
    { id: 525, spanish: 'meter', polish: 'wkładać', example_es: 'Mete la ropa en el armario.', example_pl: 'Włóż ubrania do szafy.' },
    { id: 526, spanish: 'mirar', polish: 'patrzeć', example_es: 'Mira esa película.', example_pl: 'Obejrzyj ten film.' },
    { id: 527, spanish: 'morir', polish: 'umierać', example_es: 'Todos vamos a morir algún día.', example_pl: 'Wszyscy kiedyś umrzemy.' },
    { id: 528, spanish: 'mostrar', polish: 'pokazywać', example_es: 'Muéstrame el camino.', example_pl: 'Pokaż mi drogę.' },
    { id: 529, spanish: 'mover', polish: 'ruszać', example_es: 'Mueve la silla.', example_pl: 'Przesuń krzesło.' },
    { id: 530, spanish: 'nacer', polish: 'rodzić się', example_es: 'Nací en Polonia.', example_pl: 'Urodziłem się w Polsce.' },
    { id: 531, spanish: 'necesitar', polish: 'potrzebować', example_es: 'Necesito ayuda.', example_pl: 'Potrzebuję pomocy.' },
    { id: 532, spanish: 'negar', polish: 'zaprzeczać', example_es: 'Lo negó todo.', example_pl: 'Wszystkiemu zaprzeczył.' },
    { id: 533, spanish: 'notar', polish: 'zauważać', example_es: 'Noté un cambio en su actitud.', example_pl: 'Zauważyłem zmianę w jego postawie.' },
    { id: 534, spanish: 'obtener', polish: 'otrzymywać', example_es: 'Obtuve un buen resultado.', example_pl: 'Otrzymałem dobry wynik.' },
    { id: 535, spanish: 'ocurrir', polish: 'wydarzać się', example_es: '¿Qué ocurrió?', example_pl: 'Co się wydarzyło?' },
    { id: 536, spanish: 'ofrecer', polish: 'oferować', example_es: 'Te ofrezco mi ayuda.', example_pl: 'Oferuję ci moją pomoc.' },
    { id: 537, spanish: 'oír', polish: 'słyszeć', example_es: 'No oigo nada.', example_pl: 'Nic nie słyszę.' },
    { id: 538, spanish: 'olvidar', polish: 'zapominać', example_es: 'No olvides las llaves.', example_pl: 'Nie zapomnij kluczy.' },
    { id: 539, spanish: 'pagar', polish: 'płacić', example_es: 'Voy a pagar la cuenta.', example_pl: 'Zapłacę rachunek.' },
    { id: 540, spanish: 'parar', polish: 'zatrzymywać się', example_es: 'Para el coche.', example_pl: 'Zatrzymaj samochód.' },
    { id: 541, spanish: 'parecer', polish: 'wydawać się', example_es: 'Parece una buena idea.', example_pl: 'To wydaje się dobrym pomysłem.' },
    { id: 542, spanish: 'partir', polish: 'dzielić, wyjeżdżać', example_es: 'Partimos mañana.', example_pl: 'Wyjeżdżamy jutro.' },
    { id: 543, spanish: 'pasar', polish: 'przechodzić, dziać się', example_es: '¿Qué pasa?', example_pl: 'Co się dzieje?' },
    { id: 544, spanish: 'pedir', polish: 'prosić', example_es: 'Pido un favor.', example_pl: 'Proszę o przysługę.' },
    { id: 545, spanish: 'pensar', polish: 'myśleć', example_es: 'Pienso en ti.', example_pl: 'Myślę o tobie.' },
    { id: 546, spanish: 'perder', polish: 'tracić', example_es: 'No quiero perder el tren.', example_pl: 'Nie chcę spóźnić się na pociąg.' },
    { id: 547, spanish: 'permitir', polish: 'pozwalać', example_es: 'No se permite fumar.', example_pl: 'Palenie jest zabronione.' },
    { id: 548, spanish: 'pintar', polish: 'malować', example_es: 'Pinto un cuadro.', example_pl: 'Maluję obraz.' },
    { id: 549, spanish: 'poder', polish: 'móc', example_es: 'Puedes hacerlo.', example_pl: 'Możesz to zrobić.' },
    { id: 550, spanish: 'poner', polish: 'kłaść', example_es: 'Pon el libro en la mesa.', example_pl: 'Połóż książkę na stole.' },
];